### ISSUE TITLE
How do you use Contour? Let us know!

### ISSUE THREAD

**Issue by VMmore** [projectcontour/contour#1269]
This really isn't an issue, but we'd love to hear about your use of Contour so we thought we'd post this to find out more from you.

Please feel free to leave a comment below and let us know. You can also go a step further and update the adopters file https://github.com/projectcontour/contour/blob/master/ADOPTERS.md

**Comment by so0k** [comment]
We use Contour as a DS hostnet, initially split (pre-0.14 it was insecure, but ran on tainted firewalled nodes)

We have since merged contour back with envoy pod to make the xDS connection more stable

We are using externalDNS and thus still rely on `ingress` objects instead of `ingressRoute` objects

**Comment by PeopleRange** [comment]
I have been playing with different configurations for Kubernetes Clusters to run my companies and my customer's services.

Former Setup:
GKE
3 x n1-standard-4 nodes
Istio
Cert Manager
Percona Cluster 10gb SSD
NFS Server 10GB regional SSD (Wordpress Customers (Customers Not Yet Deployed)
Average 15GB traffic on load balancer
Monthly Price: £314.50 GBP by Googles Pricing Calculator 

New Setup:
GKE
3 x g1-small Preemptiable Nodes
Estaffete Preemptiable Killer
Cillium CNI
Contour Proxy
Cert-Manager
Percona Cluster 10GB SSD
NFS Server 10GB regional SSD (Wordpress Customers (Customers Not Yet Deployed (In place ready for them)))
Traffic is expected to be the same for both clusters
Monthly Price: £38.87 GBP by Googles Pricing Calculator

Neither takes into account how much CPU or Ram is going to be needed for the WordPress customers whom I will be starting to migrate very shortly, but just the infrastructure side alone seems to be a massive price difference.

Cillium is used for network policy, cluster mesh and BPF performance over IPTables.

**Comment by michmike** [comment]
> I have been playing with different configurations for Kubernetes Clusters to run my companies and my customer's services.
> 
> Former Setup:
> GKE
> 3 x n1-standard-4 nodes
> Istio
> Cert Manager
> Percona Cluster 10gb SSD
> NFS Server 10GB regional SSD (Wordpress Customers (Customers Not Yet Deployed)
> Average 15GB traffic on load balancer
> Monthly Price: £314.50 GBP by Googles Pricing Calculator
> 
> New Setup:
> GKE
> 3 x g1-small Preemptiable Nodes
> Estaffete Preemptiable Killer
> Cillium CNI
> Contour Proxy
> Cert-Manager
> Percona Cluster 10GB SSD
> NFS Server 10GB regional SSD (Wordpress Customers (Customers Not Yet Deployed (In place ready for them)))
> Traffic is expected to be the same for both clusters
> Monthly Price: £38.87 GBP by Googles Pricing Calculator
> 
> Neither takes into account how much CPU or Ram is going to be needed for the WordPress customers whom I will be starting to migrate very shortly, but just the infrastructure side alone seems to be a massive price difference.
> 
> Cillium is used for network policy, cluster mesh and BPF performance over IPTables.
> 
> I will update comment as all customers and internal microservices are fully migrated.

this is great news and good savings @PeopleRange

**Comment by ryanelian** [comment]
Replaced our company production bare metal NGINX ingress and could not be happier.

NGINX ingress likes to kill existing connections whenever Ingress resources changed, causing some reliability issues because our Development, Staging, and Production pods are located in the same cluster for development agility.

As far as we observed, Contour does not do this. (Or it does but we didn't notice 😃)

**Comment by JTarasovic** [comment]
My company has been running k8s for over 3 years now. We run in AWS GovCloud so EKS still isn't an option for us and it certainly wasn't when we started. We've historically used a combination of ELBs and ALBs to ingress traffic to our services. It was expensive and burdensome to maintain. Everytime a service needed to ingress traffic, we'd have to roll out infrastructure (CloudFormation) changes.

We started exploring Contour late last year and I was able to roll it out and configure it relatively easily. We expose Envoy on a couple of hostPorts fronted by an NLB. Application owners expose their services via HTTPProxy resources. All of our ingress is handled by Contour as of last week and we've started deleting the "legacy" load balancers. As a result, we're expecting to save %5-10 off our our AWS bill.

**Comment by michmike** [comment]
> My company has been running k8s for over 3 years now. We run in AWS GovCloud so EKS still isn't an option for us and it certainly wasn't when we started. We've historically used a combination of ELBs and ALBs to ingress traffic to our services. It was expensive and burdensome to maintain. Everytime a service needed to ingress traffic, we'd have to roll out infrastructure (CloudFormation) changes.
> 
> We started exploring Contour late last year and I was able to roll it out and configure it relatively easily. We expose Envoy on a couple of hostPorts fronted by an NLB. Application owners expose their services via HTTPProxy resources. All of our ingress is handled by Contour as of last week and we've started deleting the "legacy" load balancers. As a result, we're expecting to save %5-10 off our our AWS bill.

this is great @JTarasovic . thank you for sharing

**Comment by ccravens** [comment]
Our team is pretty new to Kubernetes and we tried probably 4-5 Ingress controllers (Traefik, Gloo, Nginx, Kong, etc) and Contour was by far the easiest to get running and gave us the most control of the deployment. The documentation is consistent and makes it easy for teams to adapt. There are some great videos on YouTube (https://www.youtube.com/watch?v=O7HfkgzD7Z0) and Contour appears to have more functionality that we originally thought we might want in an Ingress Controller. Things we love about Contour so far:

- Simple, YAML-based Deployment (no *ctl tool required)
- Clear, concise yet powerful CRDs with lots of options
- The ability to namespace our route definitions (although I have not tried this one yet)
- Documentation that actually works and got us up and running quickly
- Based on envoy, a CNCF project

Cons:
- No cons yet! But if there are any needs in the future we'll make sure to submit issues

**Comment by michmike** [comment]
> Our team is pretty new to Kubernetes and we tried probably 4-5 Ingress controllers (Traefik, Gloo, Nginx, Kong, etc), we are really looking for that "perfect" and minimalistic kubernetes configuration. Contour was by far the easiest to get running and gave us the most control of the deployment. The documentation is consistent and makes it easy for teams to adapt. There are some great videos on YouTube (https://www.youtube.com/watch?v=O7HfkgzD7Z0) and Contour appears to have more functionality that we originally thought we might want in an Ingress Controller. Things we love about Contour so far:
> 
> * Simple, YAML-based Deployment (no *ctl tool required)
> * Clear, concise yet powerful CRDs with lots of options
> * The ability to namespace our route definitions (although I have not tried this one yet)
> * Documentation that actually works and got us up and running quickly
> * Based on envoy, a CNCF project
> 
> Cons:
> 
> * No cons yet! But if there are any needs in the future we'll make sure to submit issues

thank you so much for the kind words @ccravens . Welcome to our community!

**Comment by kriswuollett** [comment]
Hi, I'm new to k8s for a personal project to learn it along with how a modern web app / backend is built with open source tools -- nothing related to my day job. I've tried the nginx and Istio Gateway ingresses, and read about the feature set of the others. The key features that seem like the reasons I'll continue with Contour, and the others lack, are:

* Simple setup, separate from a service mesh decision which I technically don't need.
* TLS secret is separate from the client validation secret which is important when one is using cert-manager, but self-signing certs for client validation.
* The TLS client validation is built into the open source version, not limited to paid versions. Client validation is a simple way to deploy on the public internet without having user login ready yet, or to just protect admin service URL paths.
* Appears to have both gRPC and gRPC-web support. Haven't tested it yet with Contour, but reading through the docs and GitHub issues it looks like it is supported ok.

Not sure if there are issues for these already, but some things that in my limited use/experience seem lacking are:

* specifying multiple prefixes for a route to let me expose only certain portions of a service without making multiple route sections for the same service
* not sure if caSecret can be looked up another namespace through TLSCertificateDelegation, or it is the fact that I made an Opaque secret with the file instead of a kubernetes.io/tls one. right now i had to copy it into the same namespace as the HTTPProxy
* having tls.clientValidation at the route level if that would be possible with Envoy, that would let me use a single domain for an app and only require client certificates for certain paths, like admin pages
* finally... being able to route to services in different namespaces, that would let me keep third-party services / mini-apps in different namespaces, yet I still could serve them from different paths from a single domain. in a company setting that could be different teams, departments, etc. i'd guess

**Comment by youngnick** [comment]
Thanks for the comment @kriswuollett, and the reasons for using Contour.

To address your two points:
- Right now, yes, the only way to do the thing you want is to have multiple routes that go to the same service. This is because the conditions map pretty closely to filters that will be applied inside the Envoy config. I don't think it's as simple as just allowing multiple prefixes and assuming that to mean you actually want multiple routes. Right now, the config is very explicit, with limited special behavior. I can see how the syntatic sugar aspect would save some extra boilerplate, but YAML lines don't cost too much, so I'm reluctant to move away from requiring explicit config there to achieve what you want. If you'd like to talk more about the reasons, feel free to raise an issue and we can go in-depth there.
- The intended way that you route to services in different namespaces is to have a HTTPProxy in the target namespace that you include, that then includes the service. This can be a pretty basic object, but allows us to keep the service reference local.

Something like this:
```yaml
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: crossnamespace
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: crossnamespace.youngnick.dev
  includes:
  - name: includedproxy
    namespace: default
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: includedproxy
  namespace: default
spec:
  routes:
  - services:
    - name: httpbin
      port: 80
```

**Comment by kriswuollett** [comment]
Hi @youngnick, thanks for getting back to me! I ended up figuring out the cross-namespace setup. Along with the client TLS option, Contour is working fine for me.

The only thing I can think of that I'd be interested in the future is the existing feature request for rate limiting -- with it for some use cases I'd drop TLS client verification. Ideally traffic should be stopped at ingress if possible?

Current workarounds seem to be deploying envoy sidecars, waiting for the external auth feature to land in which I could bundle in a call to a limiter, or perhaps deploying Linkerd if they add it to their [Service Profiles](https://linkerd.io/2018/12/06/announcing-linkerd-2-1/#service-profiles). Istio had [deprecated their mixer policy](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limiting/), and don't have time to investigate their `EnvoyFilter`s yet.

**Comment by ccravens** [comment]
Contour makes it very easy to properly expose our Kubernetes services. But more than the technology is the team. I have not worked with an open source project that is so dedicated to ensuring users have all of the functionality they require as well as the support to get it working. Thanks to the Contour team for your work and support!

**Comment by michmike** [comment]
> Contour makes it very easy to properly expose our Kubernetes services. But more than the technology is the team. I have not worked with an open source project that is so dedicated to ensuring users have all of the functionality they require as well as the support to get it working. Thanks to the Contour team for your work and support!

thank you @ccravens!

**Comment by alexgleason** [comment]
Today I used Contour to launch https://10minutepleroma.com/, which lets users deploy a social media server on a subdomain for 10 minutes by clicking a button.

It was important I had the ability to manage routes as resources (HTTPProxy) since people could provision servers simultaneously, and I did not want to deal with the race conditions from rewriting Ingress rules.

Most of the magic happens here: https://gitlab.com/tribes-host/10minutepleroma/-/blob/develop/lib/ten_minute_pleroma/deploy.ex

Thanks for the excellent project!

**Comment by sconsurveys12345** [comment]
Contour Survey Company In Marathahalli. The company produces from survey works and data, the contour maps of the site that show the terrain gradient of the site and show the heights and depressions and the level of their gradation, with any contour interval starting from 25 cm and extending to several meters according to the customer's request, and the contour map can be used with the aerial image and thus the image appears as a background to the map Contouring as a confirmation of the contour lines on the ground. Scondesign pvt ltd known for providing Contour Survey to the clients. This Contour survey service is accomplished by our team of professionals. Contours are used to accurately represent the topography of the a terrain. S'CON SURVEYS. is one of the best construction company in Bangalore. The goal is to provide a professional touch to construction services that exceeds customer expectations.

**Comment by sconsurveys12345** [comment]
Contour Survey Company In Marathahalli. The company produces from survey works and data, the contour maps of the site that show the terrain gradient of the site and show the heights and depressions and the level of their gradation, with any contour interval starting from 25 cm and extending to several meters according to the customer's request, and the contour map can be used with the aerial image and thus the image appears as a background to the map Contouring as a confirmation of the contour lines on the ground. Scondesign pvt ltd known for providing Contour Survey to the clients. This Contour survey service is accomplished by our team of professionals. Contours are used to accurately represent the topography of the a terrain. S'CON SURVEYS. is one of the best construction company in Bangalore. The goal is to provide a professional touch to construction services that exceeds customer expectations. http://www.sconsurveys.in/our-services/civil-engineering-companies-bangalore/survey-companies-bangalore/contour-survey-companies-bangalore/
contact- 82966 98585 sconsurveys

**Comment by sconsurveys12345** [comment]
Contour Survey Company In Marathahalli. Contouring in surveying is the determination of elevation of various points on the land and fixing these points of same horizontal positions in the contour map. A contour map is very useful since it provide valuable information about the land. Contour survey is carried out at the starting of any engineering project such as a road, a railway, a canal, a dam, a building etc. Our contour survey services are cost effective and can be customized to suffice the client specifications. Primary objective of conducting these surveys is to identify any noticeable difference in elevation of the existing land. Slopes matching the same height are joined using imaginary lines that are known as contours. Contour map highlights details of the existing land condition. Based on the findings of contour survey, the design team can decide on cutting, filling, widening, and leveling the land. In this method, the contours to be located are directly traced out in the ground by locating and making a number of points on each contour. These points are then surveyed and plotted on plan and the contours drawn through them. Direct method of contouring is the most accurate but very slow and tedious as a lot of time is wasted in searching points of the same elevation for a contour. Direct Method of Contouring is suitable for small areas and where great accuracy is required. In Indirect Method of contouring, levels are taken at some selected points and their levels are reduced. Hereby in this method horizontal control is established first and then the levels of those points found. If you are interested for demo pls contact +91 8296698585. http://www.sconsurveys.in/our-services/civil-engineering-companies-bangalore/survey-companies-bangalore/contour-survey-companies-bangalore/
