### ISSUE TITLE
Lower the per connection buffer to 64k at the listener level

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1407]
Envoy assigns a 1Mb buffer to to each incoming connection. It is not clear if it consumes the whole 1Mb in one go, or that is a upper limit.

Either way, I think this should be lowered to something like 64. 

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/lds.proto#envoy-api-field-listener-per-connection-buffer-limit-bytes

**Comment by youngnick** [comment]
In #1375, this is recommended to be 32k instead. Updating title accordingly.

**Comment by davecheney** [comment]
Based on https://github.com/projectcontour/contour/pull/1797#pullrequestreview-306974148 there's a good change that this setting doesn't do what I thought it did. Moving to the backlog for more investigation.

**Comment by BerGer23** [comment]
Hi, 
I am in the process of reviewing the Envoy configuration Contour generates for us.

Looks like one of the differences between Contour Envoy configuration and [the suggestions from the Envoy team for running on the edge](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge) is the lack of defining this buffer for Listener & Cluster.

Searching for this led me to this ticket here.
1. Is not overriding the Envoy default done intentionally?
2. Since this ticket has been around for a while, could anybody tell me what's the latest on this?

Thanks in advance folks!

**Comment by skriss** [comment]
@BerGer23 I think it makes sense to look into using Envoy's recommended settings here, but we also need to ensure we understand the impact on existing users of changing the settings. One possible approach here would be to change the default setting, but also expose a tuneable to allow users to modify the setting to something else if needed.

Have you done/are you able to do any testing around changing this setting, and observing any perf or behavior changes?

**Comment by BerGer23** [comment]
Hi @skriss, sorry about the late answer.
I'm afraid I don't have any constructive input on this currently, neither on the performance nor behavioural side - happy to see this is actively worked on though.
