### ISSUE TITLE
HTTPProxy not pushing updates to Envoy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1514]
**What steps did you take and what happened:**
When Contour first spins up, it builds a DAG and the config is pushed down to Envoy, however, if an HTTPProxy changes, the DAG is rebuilt, but Envoy isn't updated dynamically.

**Comment by davecheney** [comment]
Can you verify this with a `contour cli` session running in another window and the editing a HTTPProxy object?

**Comment by davecheney** [comment]
Oops. This was my fault. The underlying cause is shadowing of `hints` here https://github.com/projectcontour/contour/blob/master/internal/contour/cond.go#L64

The result is if you register with a hint, which envoy does for RDS, EDS, and CDS(?) then `hints` would be set to the hint registered during `Register`, line 64 would not trigger because the length of things hints was > 0, however the following lines would also not trigger because the map `m` built from the outer hints was empty.

The end result is `contour cli rds` works, but `contour cli rds ingress_https` would only receive one update. 

Fix coming up.
