### ISSUE TITLE
internal/contour: need to assert that route objects with header conditions sort properly

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#1579]
https://github.com/projectcontour/contour/pull/1576#issuecomment-535402749

**Comment by jpeach** [comment]
@dfc and I discussed this. We agreed that header matching should follow the same longest-match principle that path matching uses (i.e. matching 3 header is more specific than matching 2 headers, so the 3 header route should be matched first).

For quality-of-implementation reasons, we should also order the header match set, since that will ensure that the hash of the envoy route entry remains stable and that we won't make more envoy updates than necessary.

**Comment by jpeach** [comment]
I'll start working on this next week.
