### ISSUE TITLE
User Experience with HTTPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#1598]
## Background:

A key feature that Contour provided with `IngressRoute` and now `HTTPProxy` is a way to safely enable ingress with teams spread across namespaces. 

A likely scenario is that `root HTTPProxies` are managed by Administrators in a namespace that users do not have access. Users also will have `Includes` defined to their HTTPProxies which delegate path prefixes and headers across namespaces (i.e Conditions). 

Additionally, users working in their team namespace need to self-manage their proxies so that they can route traffic to applications (i.e. services). 

## User Story

As a user working in a namespace within a single Kubernetes cluster, I want to be able to self-manage my HTTPProxy resources and understand what Includes have been added to my proxies from other parent/root HTTPProxy resources.

## Problem

Users have no visibility as to what conditions are delegated to them from parent/root HTTPProxy resources. This makes understanding what Conditions are delegated to them very difficult.  Users also need to understand exactly what names are used in the parent HTTPProxy to properly link them together and enable the delegation.

**Comment by stevesloka** [comment]
https://github.com/projectcontour/contour/issues/2495#issuecomment-728562486

**Comment by xaleeks** [comment]
Kind of an old issue so not sure if this is still on your mind @stevesloka.  How do you envision the child leveraging this info about the parent  I’m just thinking about it as this subdomain with the relevant resources have been assigned to him, so does this facilitate privilege escalation in anyway?  

I kind of imagined it the other way around actually, when a child resource is modified in some meaningful way, Contour would append some kind of warning to the status of the parent/root object

**Comment by stevesloka** [comment]
https://github.com/projectcontour/contour/pull/3146

**Comment by youngnick** [comment]
I don't think this is a privilege escalation risk @xaleeks. This is more about telling a HTTPProxy owner where their route is included into, and with what conditions, so that you have a way to know what different requests will look like. This is important because you can have a HTTPProxy included into multiple parents, and there's currently no way to know that's happening.

In particular, this is important because of something like this:
- parent proxy for `www.foo.com` includes a proxy from `marketing` namespace, proxy name is `blog`. It includes that resource with a prefix Condition of `/blog`.
- So all requests coming in to that service will come in with their path set to `http://www.foo.com/blog`. 
- If the service backing the `blog` HTTPProxy is not expecting requests at that path (say, it's expecting them at `/`), then you'll get 404s.
- *If the `blog` HTTPProxy owner knows this*, they can configure a PrefixRewrite to rewrite `/blog` to `/` as the request is sent on to the service, and everything will work.

Currently there's no way for the `blog` HTTPProxy owner to know what conditions their proxy has been included with, so this issue covers doing something to make that visible.

**Comment by xaleeks** [comment]
Thanks Nick, apologies for the late response.  It sounds like we're saying then is that the includes construct for multi delegation is broken or at least incomplete right now.  If we assume there are actually multiple personas here, by that I mean the parent HTTPProxy admin and the child HTTPProxy admin are two different individuals, the child has no idea how his HTTPProxy is configured by any parents.  So while we have the Includes and PrefixRewrite to achieve this parent child behavior, it depends on offline communication between the two admins, it's not actually codified.  To me, that feels sort of incomplete.  

So should we prioritize https://github.com/projectcontour/contour/issues/2495 then

**Comment by youngnick** [comment]
Yes, we should prioritize #2495, agreed.
