### ISSUE TITLE
Tooling to migrate from IngressRoute to HTTPProxy

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#1689]
**Describe the solution you'd like**

Tooling to help users migrate their applications from the IngressRoute CRD to the new HTTPProxy CRD. I'm thinking of some tool that reads a set of IngressRoute definitions and emits the equivalent HTTPProxy ones.

**Anything else you would like to add:**

Existing Contour users will need to migrate their services from IngressRoute to HTTPProxy. This migration would take them less effort in there is tooling to support it, and if there's less effort, users will be able to migrate sooner.

There are a few decisions to make about what form this tooling should take
- Should it inspect a cluster or a set of YAML files, or both?
- Should it just emit YAML or should it also update the cluster?
- What should happen to incompatible fields (needs a detailed design document)
- How should a user invoke the tool (contour subcommand, kubectl plugin, standalone command, etc)?
- For delegations vs. includes there's probably some complexity around how to structure the output documents

Related to #1561

**Comment by stevesloka** [comment]
We should also look to see if this tool can help move the `contour.heptio.com` annotations for users in the event they are just using k8s Ingress.

**Comment by youngnick** [comment]
I'll take this one, and write up a design. To answer some of the questions:
- I think this should definitely be a subcommand, like `contour certgen`
- Also similarly `contour certgen`, it should ideally allow either reading from yaml or cluster, and outputting to either yaml or cluster. This should be possible because practically, step 1 here is 'get the source objects into a struct' anyway, and then outputting should be pretty pluggable as well.

Putting this into a subcommand gives us an option down the road - to have a Job that runs to produce an initial port of the config for users, in the same way that `contour certgen` runs to generate the gRPC TLS certs.

For outputting incompatibilities or other problems, I think maybe using an annotation on the object might be okay. Not because we want to read the annotation, but because it puts the errors into the YAML/object directly. It probably also makes sense to directly set `ingress.class` to a non-operable value by default, to approximate a 'dry-run'.

So, next steps here:
- I'll start working on a design outline and get a draft PR up with the broad-strokes bits asap. That way we can all ensure we're in agreement on the approach.
- Once that's done, I'll start more detailed design work, going through the two specs and writing down how I think we should reconcile the differences. The delegation-inclusion translation is pretty tricky, so will require careful thought.

**Comment by davecheney** [comment]
Thanks for working on this. 

I think it would be useful to state the design criteria up front? Ie. should the translation be online or offline? If it’s the former, what downtime guarantees are we giving? 

Personally I think it’s fine to write a tool in an offline mode to translate yaml that users can apply later.

**Comment by jpeach** [comment]
> On 12 Nov 2019, at 5:57 pm, Dave Cheney <notifications@github.com> wrote:
> 
> Thanks for working on this. 
> 
> I think it would be useful to state the design criteria up front? Ie. should the translation be online or offline? If it’s the former, what downtime guarantees are we giving? 
> 
> Personally I think it’s fine to write a tool in an offline mode to translate yaml that users can apply later. 

The other interesting criteria is who should be deleting the old object.

**Comment by davecheney** [comment]
I feel strongly that only a human should do that.

**Comment by youngnick** [comment]
On reflection, here are my proposed design criteria:
- The tool must run offline and only output YAML locally, not to a cluster. (going straight to a cluster is too tricky)
- The tool must accept local YAML as input, and may pull from a kubernetes context and namespace.
- The tool should have a way to force a person to look at the objects before applying.
- The tool should be delivered as a subcommand (makes the distribution much easier).

The flow for use of the tool is therefore:
- Run the tool against your source objects
- Inspect the generated YAML and check that it's doing what you think, and ensure that the YAML is apply-able.
- Apply the HTTPProxy objects and verify that nothing changes.
- Remove the IngressRoute objects and verify that nothing changes.

There's no way around the fact that a human will need to do all of these steps. They are too specific to a cluster, and too easy to get wrong, to do automatically.

For incompatible fields and delegation-to-inclusion translation, that will require a detailed design doc.

I had intended to put the first few sections of the design doc up as a draft PR to answer the design criteria question, but this is quicker and better, thanks @davecheney.

**Comment by davecheney** [comment]
SGTM but the final two steps are reversed. As I understand it the same vhost mentioned across both ingressroute and httpproxy invalidates both of them. 

Perhaps as part of this work we can change this ordering such that a HTTPProxy and ingressroute that share the same vhost will invalidate the latter which leaving the former active. That should make the steps you outlined work, and it’s a pretty straight forward upgrade path.

**Comment by davecheney** [comment]
What’s the rationale for making this a sub command? This command runs locally, not inside k8s. Reusing cmd/contour for this feels, a little monolithic

**Comment by youngnick** [comment]
Only that it was easier for packaging etc, and by extension from `contour certgen`. You're right, it doesn't really make much difference if it's a separate command. Separate command does mean separate docker image as well (in case people want to run it that way).

**Comment by davecheney** [comment]
Why docker for a single binary? -- this is a one case that might be a good
fit for go-releaser

**Comment by youngnick** [comment]
I just assumed. I guess this is an area I don't know enough about. I've updated the summary accordingly.

**Comment by davecheney** [comment]
This is something where the Valero folks can help us

**Comment by youngnick** [comment]
I'll make a note for myself to talk to them about it at Kubecon.

**Comment by youngnick** [comment]
[Version 0.1 of ir2proxy](https://github.com/projectcontour/ir2proxy/releases/tag/v0.1.0) was released on the 10th of December 2019. The repo is at [ir2proxy](https://github.com/projectcontour/ir2proxy/), and issues are being tracked [here](https://github.com/projectcontour/ir2proxy/issues). I'll close this issue out now.

The process of refining the tool will continue as we move towards removing IngressRoute support hopefully in early 2020.
