### ISSUE TITLE
Makefile: Misspell check missing docs directory

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2130]
The check for spelling errors is missing the site/docs directories and aren't being checked for errors.

**Comment by jpeach** [comment]
@stevesloka Is this done?

**Comment by stevesloka** [comment]
No, the spelling doesn't check things correctly. If you open a doc in the site, for instance, misspell something, it won't find it. In the tests I did, the tool didn't find errors when it should have.

**Comment by jpeach** [comment]
I looked at this a bit and I think the problem is that `misspell` isn't a spell checker, it just corrects common misspellings. If the misspelling isn't already known to it, it won't do anything.

Unless we want to pull in a complete spell checker (e.g. envoy uses [aspell](http://aspell.net) with 800 lines of python to handle special cases), I'm inclined to close this out.
