### ISSUE TITLE
HealthCheckPolicy missing from TCPProxy

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2140]
When the healthcheck logic got moved from the service to the route, it didn't get added back to the tcpproxy in HTTPProxy (https://github.com/projectcontour/contour/pull/1630). 

// cc @bgagnon

**Comment by bgagnon** [comment]
For context, we used this feature with _IngressRoute_ to proxy the Kubernetes API in L4 mode [1]. The _Endpoints_ object backing the `kubernetes` service in the `default` namespace is managed externally in our distribution (Rancher) because the API servers are not running in pods.

Therefore, the list of IPs for the Envoy cluster is static and has no guarantee of readiness/liveness. Using the active health checking feature is convenient here.

---
[1] L7 is not possible with K8S due to the fancy SPDY protocol upgrades in play with `kubectl exec` and `kubectl port-forward` which are not supported in Envoy.

**Comment by davecheney** [comment]
This is likely my fault.

The underlying reason, for the best of my recollection is the health check stanza that is used for l7 http like things was not appropriate for l4 tcp things because it contained a path element.

I believe the idea at the time was to duplicate the structure, remove the http specific components and apply this modified type to the tcpproxy stanza.

On 23 Jan 2020, at 07:21, Benoit Gagnon <notifications@github.com> wrote:

﻿

For context, we used this feature with IngressRoute to proxy the Kubernetes API in L4 mode [1]. The Endpoints object backing the kubernetes service in the default namespace is managed externally in our distribution (Rancher) because the API servers are not running in pods.

Therefore, the list of IPs for the Envoy cluster is static and has no guarantee of readiness/liveness. Using the active health checking feature is convenient here.

________________________________

[1] L7 is not possible with K8S due to the fancy SPDY protocol upgrades in play with kubectl exec and kubectl port-forward which are not supported in Envoy.

**Comment by stevesloka** [comment]
I'm double-checking IngressRoute as well in v1 code, from my first glance I don't see this even implemented still for IngressRoute.TCPProxy.

**Comment by davecheney** [comment]
It’s likely that if it’s missing from ingressroute tcpproxy it is because of the same reasons.

On 23 Jan 2020, at 07:57, Steve Sloka <notifications@github.com> wrote:

﻿

I'm double-checking IngressRoute as well in v1 code, from my first glance I don't see this even implemented still for IngressRoute.TCPProxy.

**Comment by stevesloka** [comment]
@davecheney here's my plan then if this makes sense. 

1. Work on a PR to fix `IngressRoute` by adding back TCPProxy health checks, ignoring the `path component`. 
2. A second PR to introduce a new field, `TCPHealthCheckPolicy` which essentially doesn't have the `path` and `host` fields as options but retains the other fields, `IntervalSeconds`, `TimeoutSeconds`, etc

**Comment by davecheney** [comment]
SGTM!

**Comment by stevesloka** [comment]
> Ingressroute is deprecated, please do not touch it. If we touch it we undermine our own position that its deprecated.

Bah missed this in GH emails. I understand it's deprecated, my thought was to fix it since we broke it and users who needed to upgrade to a version of Envoy without CVE's could but not yet migrate to HTTPProxy.

**Comment by davecheney** [comment]
I think there are some crossed wires here

In 0.15, ingressroute supported health checking on tcp proxy services 

https://github.com/projectcontour/contour/blob/release-0.15/apis/contour/v1beta1/ingressroute.go#L81

In 1.0 the situation was unchanged

https://github.com/projectcontour/contour/blob/release-1.0/apis/contour/v1beta1/ingressroute.go#L74

For httpproxy in 1.0

Healthcheck policy was moved from the service object to the containing route object and renamed HTTPHealthCheckPolicy

https://github.com/projectcontour/contour/blob/release-1.0/apis/projectcontour/v1/httpproxy.go#L158

No corresponding field was added to TCPProxy, but the intention was to duplicate HTTPPhealthCheckPolicy, remove the l7 elements, so call it, TCPHealthCheckPolicy, and add it to TCPProxy.

In 1.1 the situation is unchanged.

I don't see there is any work we need to do for IngressRoute.

**Comment by stevesloka** [comment]
It's in the spec for IngressRoute, but it's not used anywhere in dag, so if users set that field in and IngressRoute using Contour v1.0+, it has no effect on the resulting config we send to Envoy (from what I can see): https://github.com/projectcontour/contour/blob/release-1.0/internal/dag/builder.go#L882-L884

**Comment by davecheney** [comment]
Yes, I agree that's an oversight, looking back to earlier releases I don't believe it you could ever supply a heatlth check policy for a tcpproxy's service.

https://github.com/projectcontour/contour/blob/release-0.15/internal/dag/builder.go#L660

This is unfortunate, but I don't think there is an argument that we ingrssroute users lost anything, it never worked in the first place.
