### ISSUE TITLE
Contour should document how to use alternatives to certgen for securing traffic between contour and envoy

### ISSUE THREAD

**Issue by davecheney** [projectcontour/contour#2149]
Notwithstanding @tsaarni 's efforts to make certificate rotation easier to accomplish, we should acknowledge that certgen is not going to grow beyond its current role of supporting the example deployments of Contour. To that end we should investigate and document the procedure for using alternative solutions like cert-manager or vault to maintain the certificates used by contour and envoy.

**Comment by jpeach** [comment]
Ref #2143

**Comment by ryanelian** [comment]
Big yes to using cert-manager replacing cert-gen.

Got hit by a deployment issue with contour-certgen job: https://github.com/projectcontour/contour/issues/2150

**Comment by tsaarni** [comment]
I did a small proof of concept where I used [cert-manager](https://cert-manager.io/) instead of certgen for issuing xDS certificates.  At this point running this requires a fork of  Contour with #2333 and Envoy with https://github.com/envoyproxy/envoy/pull/10163.  

I did changes in deployment manifest by editing the final rendered version of the example manifest [contour.yaml](https://github.com/projectcontour/contour/blob/6eca7b4ccd542e09d1034cc23be49297c15a2d39/examples/render/contour.yaml) on-the-fly with a kustomize patch.  I did not create PR yet since I'm bit doubtful **how to best maintain** the manifests for these two deployment alternatives (certgen and cert-manager)?

Here is link to the PoC https://github.com/projectcontour/contour/compare/master...Nordix:cert-manager 

Summary of changes in the manifest that I think are necessary:

* removed ServiceAccount for certgen
* removed Role for certgen
* removed RoleBinding between the certgen service account and role
* removed certgen Job
* removed cacert volume mount from Envoy DaemonSet (both init container and main) since  `cacert` secret does not exist anymore. Cert-manager writes CA cert in same secret with TLS cert and key.
* changed `contour bootstrap` argument from `--envoy-cafile=/ca/cacert.pem` to `--envoy-cafile=/certs/ca.crt` in Envoy DaemonSet, since cert-manager names the CA certificate as `ca.crt`
* removed cacert volume mount from Contour Deployment
* changed `contour serve` argument from `--contour-cafile=/ca/cacert.pem` to `--contour-cafile=/certs/ca.crt `in Contour Deployment

**Comment by jpeach** [comment]
xref #2088 

Moving to kustomize will help, since that can split the certgen deployment into an optional base. Rewriting command flags in kustomize feels fragile to me, but as you found, it's doable.

**Comment by jpeach** [comment]
> I did changes in deployment manifest by editing the final rendered version of the example manifest [contour.yaml](https://github.com/projectcontour/contour/blob/6eca7b4ccd542e09d1034cc23be49297c15a2d39/examples/render/contour.yaml) on-the-fly with a kustomize patch. I did not create PR yet since I'm bit doubtful **how to best maintain** the manifests for these two deployment alternatives (certgen and cert-manager)?

@tsaarni Can you take a look at https://github.com/projectcontour/contour/pull/2474 and see whether that simplifies your deployment? While this change separates out the certgen job, you would still need to update the certificate filenames.

**Comment by karjov** [comment]
> I did a small proof of concept where I used [cert-manager](https://cert-manager.io/) instead of certgen for issuing xDS certificates. At this point running this requires a fork of Contour with #2333 and Envoy with [envoyproxy/envoy#10163](https://github.com/envoyproxy/envoy/pull/10163).
> 
> I did changes in deployment manifest by editing the final rendered version of the example manifest [contour.yaml](https://github.com/projectcontour/contour/blob/6eca7b4ccd542e09d1034cc23be49297c15a2d39/examples/render/contour.yaml) on-the-fly with a kustomize patch. I did not create PR yet since I'm bit doubtful **how to best maintain** the manifests for these two deployment alternatives (certgen and cert-manager)?
> 
> Here is link to the PoC [master...Nordix:cert-manager](https://github.com/projectcontour/contour/compare/master...Nordix:cert-manager)
> 
> Summary of changes in the manifest that I think are necessary:
> 
> * removed ServiceAccount for certgen
> * removed Role for certgen
> * removed RoleBinding between the certgen service account and role
> * removed certgen Job
> * removed cacert volume mount from Envoy DaemonSet (both init container and main) since  `cacert` secret does not exist anymore. Cert-manager writes CA cert in same secret with TLS cert and key.
> * changed `contour bootstrap` argument from `--envoy-cafile=/ca/cacert.pem` to `--envoy-cafile=/certs/ca.crt` in Envoy DaemonSet, since cert-manager names the CA certificate as `ca.crt`
> * removed cacert volume mount from Contour Deployment
> * changed `contour serve` argument from `--contour-cafile=/ca/cacert.pem` to `--contour-cafile=/certs/ca.crt `in Contour Deployment

Hello there, running into changing using cert-manager for contour, is there any kind of blog post or guide how to setup cert-manager for contour and would you be willing to share?

**Comment by tsaarni** [comment]
Hi @karjov. I'll work on a proposal for the Bitnami Contour helm chart. You can follow the progress here: https://github.com/bitnami/charts/pull/29416
