### ISSUE TITLE
Allow current namespace in leader election config

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2208]
The default leader election configuration is:

```Go
		LeaderElectionConfig: LeaderElectionConfig{
			LeaseDuration: time.Second * 15,
			RenewDeadline: time.Second * 10,
			RetryPeriod:   time.Second * 2,
			Namespace:     "projectcontour",
			Name:          "leader-elect",
		},
```

If an operator deploys Contour to a non-default namespace, then also have to change the leader election configuration in the Contour ConfigMap. To make this easier, we can define and empty `Namespace` parameter to mean "the current namespace", so that Contour looks for the leader election config in whichever namespace it has been deployed to.

xref: #2207

**Comment by stevesloka** [comment]
I think we should actually remove the `namespace` parameter from the config all together and just use the downward api to pass in the current namespace in which Contour is running. I can't think of a reason you'd want  to have Contour run in a different namespace than where this election happens. 

Thoughts @youngnick?

**Comment by jpeach** [comment]
My only concern here is backwards compatibility.

**Comment by youngnick** [comment]
We should absolutely just default it to using the current namespace. If we're doing that with the downward api though, then it has to be passed as an env var, and we already have the infrastructure (kingpin command line flag with env var override) available to do that. So, I think we should leave the command line flag there.

If we keep the config file option, then it needs to be listed as "<Contour namespace>" or something invalid as the default, so that people know they don't need to set it. I'll be honest, I'm inclined to remove it from the config file. I know @jpeach has thoughts there though.

**Comment by stevesloka** [comment]
My thought was to remove the config file option. It won't break users if they define the value going forward. I don't understand why we provide any way for users to configure this field, so in my mind, we should do the following:

1. Mark the configurations as deprecated
2. Use the downward api to get the namespace but allow the config options to override
3. In a future version fully remove the configuration capabilities

**Comment by stevesloka** [comment]
Contour now uses the ENV variable `CONTOUR_NAMESPACE` as the default for the namespace. (https://github.com/projectcontour/contour/blob/67f6207604ebb34412b7d8b125cdff410bbe4401/cmd/contour/servecontext.go#L183). That ENV var is populated by default via the downward API: https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml#L77-L81

I think this is all resolved at this point since deploying Contour into any namespace should work out of the box.
