### ISSUE TITLE
Getting started guide does not work

### ISSUE THREAD

**Issue by gottwald** [projectcontour/contour#2298]
**What steps did you take and what happened:**
I was trying to dig into the project by following the getting started guide here: https://projectcontour.io/getting-started/

The guide links to these manifests which I applied https://raw.githubusercontent.com/projectcontour/contour/release-1.2/examples/render/contour.yaml

I made a minor change for the envoy service object to use a proper Google LB since I'm using GKE.

The envoy pods never became ready because the readiness check was failing.
The manifests configure the readiness probe to access `/ready` on port `8002` but there is no listener on that port.

Also the init container (`contour bootstrap`) does not emit a config which adds such a listener.

**What did you expect to happen:**

Everything starting up healty

**Environment:**

- Contour version: 1.2.0
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes installer & version: GKE (1.14.8-gke.33)
- Cloud provider or hardware configuration: Google Cloud
- OS (e.g. from `/etc/os-release`):
```
$ cat /etc/os-release
BUILD_ID=11647.348.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=41e9e2e85e50dadce3887070595b89c017e37a2c
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=73
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=73
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

**Comment by davecheney** [comment]
Thank you for reporting this issue.

Port 8002 is not part of the bootstrap configuration, it is configured once envoy connects to contour.

Can you please confirm that your contour pods are up and running and envoy can connect to them. If you can include logs from both envoy and contour pods that will be of great assistance.

On 29 Feb 2020, at 02:59, Ingo Gottwald <notifications@github.com> wrote:

﻿

What steps did you take and what happened:
I was trying to dig into the project by following the getting started guide here: https://projectcontour.io/getting-started/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprojectcontour.io%2Fgetting-started%2F&data=02%7C01%7Ccheneyd%40vmware.com%7C1fa04344a74047f1adab08d7bc6734d0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637185023761245054&sdata=D6cBEQscycP4m0ow5aUXIJRQX5Zj7%2BVZBSM0EjYd4pA%3D&reserved=0>

The guide links to these manifests which I applied https://raw.githubusercontent.com/projectcontour/contour/release-1.2/examples/render/contour.yaml<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fprojectcontour%2Fcontour%2Frelease-1.2%2Fexamples%2Frender%2Fcontour.yaml&data=02%7C01%7Ccheneyd%40vmware.com%7C1fa04344a74047f1adab08d7bc6734d0%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637185023761255042&sdata=ZDxr6Pbqic%2Fw9Di%2FOHZ490Tm%2FVrcAs7Q%2BAvk9xp%2BOM0%3D&reserved=0>

I made a minor change for the envoy service object to use a proper Google LB since I'm using GKE.

The envoy pods never became ready because the readiness check was failing.
The manifests configure the readiness probe to access /ready on port 8002 but there is no listener on that port.

Also the init container (contour bootstrap) does not emit a config which adds such a listener.

What did you expect to happen:

Everything starting up healty

Environment:

  *   Contour version: 1.2.0
  *   Kubernetes version: (use kubectl version): Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
  *   Kubernetes installer & version: GKE (1.14.8-gke.33)
  *   Cloud provider or hardware configuration: Google Cloud
  *   OS (e.g. from /etc/os-release):

$ cat /etc/os-release
BUILD_ID=11647.348.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=41e9e2e85e50dadce3887070595b89c017e37a2c
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=73
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=73
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos

**Comment by davecheney** [comment]
@gottwald ping

**Comment by gottwald** [comment]
Sorry, I was offline over the weekend.

This is getting awkward.
I deleted my setup completely from the cluster (including the namespace) after I created the issue on Friday.
Today I tried to reproduce it from the same yaml and I don't succeed.

Port 8002 not being part of the bootstrap makes things a bit clearer about the situation.

When I had the problem, the contour log seemed fine but envoy logged something like:

```
[bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

I was able to `kubectl exec` into one of the envoy pods and verify that is was possible to connect via tcp to the `contour` svc.

So I'm not sure why envoy was having connection failures.
Suspecting some mistake on my side.

Just to be sure: A possible TLS cert error would produce a different log message, wouldn't it?

But all in all, I can't reproduce it right now.
So I guess we can close this issue until I or somebody else hits it again.

**Comment by stevesloka** [comment]
Hey, @gottwald seems like everything is working now. Did your pods come back healthy when you tried the 2nd time?

**Comment by gottwald** [comment]
Yes, with a complete fresh attempt they were up and ready.

**Comment by stevesloka** [comment]
Good to hear @gottwald!
