### ISSUE TITLE
Routable services across multiple clusters

### ISSUE THREAD

**Issue by michmike** [projectcontour/contour#2326]
It is sometimes important to be able to deploy components of a service into multiple clusters (for HA, locality, etc). As a result, i need a solution that will enable me to do 
a. Discovery of the different clusters that contain my service
b. Route traffic to the different clusters using my load balancing policy

Support should be scoped to fqdn-capable routing (tls, tcp, http, http)

**Comment by jpeach** [comment]
Seems related to  Multi-Cluster Services API proposal presented to sig-network

https://docs.google.com/document/d/1hFtp8X7dzVS-JbfA5xuPvI_DNISctEbJSorFnY-nz6o

**Comment by jpeach** [comment]
Should this still be in the prioritized backlog? It seems like a research project that needs scoping.

**Comment by michmike** [comment]
we can leave it there for now. there are asks on this from users, so part of the initial work includes scoping/research and potentially a prototype/POC

**Comment by jpeach** [comment]
> we can leave it there for now. there are asks on this from users

Can you please add links to those?

**Comment by xaleeks** [comment]
Been over a year since Michael raised this but let’s keep leveraging this ticket for hashing out the MCS (multi cluster service) and MCI (multi cluster ingress) work.   

JFYI, the service discovery across multiple k8s clusters piece consistently comes back to https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api

Let’s perhaps just have an open discussion on this topic here.  Do we feel the original request raised here is something we want to solve?  If so, where does Contour fit into the whole MCS story.  Thoughts from @youngnick  @stevesloka  @sunjayBhatia  @skriss ?

**Comment by stevesloka** [comment]
I think there are some interesting use-case that can help out here, just a matter of what we want to tackle as there are several other implementations/designs out in the wild that could also help solve some of these issues. 

//cc @rosenhouse
