### ISSUE TITLE
merge duplicate slashes in paths

### ISSUE THREAD

**Issue by seangaffey** [projectcontour/contour#2344]
**What steps did you take and what happened:**

We have come across an issue while testing contour.
We have found some urls which are not being routed with contour but are with nginx
For example, a route defined in the ingress object of a service:

/example/route/service/

If the client makes this call:

https://somehost.com/example/route//service/library.json

on contour this returns 404 but on nginx it resolves

If we remove the double forward slash it works:

https://somehost.com/example/route/service/library.json

Is this handling around forward slashes a known issue in contour?

In this envoy documentation https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
I can see a 'merge_slashes' configuration option. Is this something which is possible to expose in contour?

**What did you expect to happen:**

I expected contour to merge the duplicate slashes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version: 1.1
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by prateekjainaa** [comment]
We are also facing this issue, where `//` is different from `/` in urls. for example,

` http://abc.com/index.html`

is different from

`http://abc.com//index.html`

as envoy allows this configuration, can we get this as option in helm while installing contour?

Regards,
Prateek

**Comment by prateekjainaa** [comment]
Hi @michmike, 

  Is there any tentative time frame for this fix?

Regards,
Prateek

**Comment by michmike** [comment]
> Hi @michmike,
> 
> Is there any tentative time frame for this fix?
> 
> Regards,
> Prateek

merged already as per the commit from Steve above. next release of Contour (in about ~3-4 weeks) should have it in.

**Comment by maplain** [comment]
@michmike @stevesloka 

Does it make sense to expose this configuration in Contour?

Sometimes two consecutive slashes make sense eg: https://cors-anywhere.xx.xx/https://google.com. To be more specific, running a service like https://github.com/Rob--W/cors-anywhere/ behind Contour is impossible now because the appended url will become `https:/google.com`.

**Comment by youngnick** [comment]
We can possibly look at adding something to disable this if you really need it, but I don't think that CORS Anywhere is a good example, because Contour can configure CORS headers for you.

**Comment by maplain** [comment]
Thanks @youngnick !

It's great to learn Contour is able to add CORS headers! I somehow missed it in the doc. The service I mentioned above does a little bit more than adding those headers, though I guess I could probably leverage the header condition to achieve the same thing(like whitelisting and rate limiting).

With that being said, it'll still be helpful to have that option exposed. seems like @prateekjainaa also mentioned a use case above..

**Comment by youngnick** [comment]
I understand that it would be helpful, but I'd like to understand more why. What's the specific use case that it's helpful for? We try not to add configuration settings without specific information about what use case they're solving for, as it's code we need to maintain forever, and multiplies the size of the testing matrix.

**Comment by maplain** [comment]
As far as I can tell, it's not against the standard: https://stackoverflow.com/a/20524044. And browser doesn't do anything about it. So IMHO, how it is used is an application behavior, which Proxy probably should not care. Also Nginx and Envoy both have that config exposed, I just think it's intuitive to have it exposed as well in Contour so people could manually tune it.

With that being said, I think it depends on if we think of Envoy config as part of Contour API.

If we're offering Contour as an opinionated API on top of Envoy, it makes sense to be cautious about what we add to the support matrix. Otherwise, if Contour aims to offer an easy and flexible out-of-box Envoy experience without losing its configuration flexibility, then maybe we could simply warn users when they cross the boundary.

My personal use case is to append an URL to another one for proxying, or simply running https://github.com/Rob--W/cors-anywhere behind Contour(could directly expose it on the internet as well, but want to save one Public IP also get the SSL automatically done). Judging from the stars on that repo, it may not be a super rare use case.. :)

Maybe @prateekjainaa has other use cases in mind.

**Comment by prateekjainaa** [comment]
@maplain Here are my 2 cents to this:

1. I dont mind if option to disable this behavior is exposed as a configuration. But then it has to be decided whether it would be per application or per installation of contour.

2. Our issue was that once we started to port applications to contour, it simply broke some of their behavior and there was no option to control this behavior. 

3. IMO, any software should be simple/easy to use and must satisfy majority of existing use-cases with minimal configuration required from their end.
