### ISSUE TITLE
Pull sorting methods into a helper package.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2376]
The fix for #2347 changes the named of the `RouteConfiguration` objects that Contour generates. This, in turn changes the sort order, which in validates the comparisons in `e2e/rds_test.go`. The basic problem here is that the tests are encoding a specific sort order, but that doesn't really matter (and tests should be insensitive to it).

So, if we hoist the sort methods into their own package, the tests can sort appropriately before comparing. Alternatively, we could switch over to `testify/assert` and use [ElementsMatch](https://godoc.org/github.com/stretchr/testify/assert#ElementsMatch) to ensure that the tests don't depend on sort order.

**Comment by jpeach** [comment]
Note that we can't use the `ElementsMatch` approach, because in most cases tests compare container objects which have embedded fields that are sorted slices. There's no way to pass down  whether we should do a order-insensitive comparison for some fields.

**Comment by youngnick** [comment]
No objection from me, the important to remember though is that, currently, the hard-coded sort order is a proxy for ensuring that sort orders are *stable*.

That is needed because we don't currently keep track of what information we have sent to Envoy, so we want identical updates to actually be identical, or Envoy will create new configurations for no-op updates, using more memory.
