### ISSUE TITLE
Contour CLI help should sort the option flags.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2397]
**Please describe the problem you have**

When a Contour subcommand has a log of option flags, it is hard to find the one you want because the `--help` output doesn't sort them. Sorting the flags by name would make it easier to read and to find a flags in the category you are looking for.

**Comment by jpeach** [comment]
Hopefully, the kingpin library has a knob that sorts.

**Comment by pickledrick** [comment]
Kingpin doesn't appear to have a configurable way of setting flag order. Would we be open to alphabetically reorganising the current set of flags?

**Comment by jpeach** [comment]
What did you have in mind?

**Comment by pickledrick** [comment]
1. A custom usage template in kingpin, with an alphabetic sort function (potentially from sprig). However it doesn't seem possible to include template functions currently in Kingpin. Since kingpin is no longer actively maintained. Should we investigate an alternative? The original author of Kingpin now has [Kong](https://github.com/alecthomas/kong) 
2. Manually re-ordering the short list that we currently have

**Comment by youngnick** [comment]
I think that manually ordering the list we currently have is probably better, whether it's alpha or by function or something.
