### ISSUE TITLE
Configure namespace selector to isolate contour controllers so that it process httpproxy/ingress only from matching ns labels

### ISSUE THREAD

**Issue by sudeeptoroy** [projectcontour/contour#2402]
A multi-tenant K8s cluster can supports multiple contour controllers.  A httpproxy definition is  processed by all contour controllers installed on the cluster. 

The requirements is to isolate contour controller and serves certain namespaces selected via label.

This requirement can be achieved via class annotation but this solution is tedious.
1. class annotation does help but it enforces all the users to configures a class annotation. 
2. writing a policy to mutate with a proper class annotation is also difficult in scenarios where there are multiple controllers and mutation logic cannot determine the default controller user is targeting.
3. A wrong httpproxy configuration in a cluster affects all the contour controller which processes it.

Instead if we can configure contour controller to process httpproxy/ingress definition filtered via a namespace selector the solution becomes elegant and we dont need to enforce a lot of rules for the end users.

**Comment by stevesloka** [comment]
Hey @sudeeptoroy, so to restate the ask, you'd like a way to pass a set of namespaces to Contour which defines which namespaces contour will look for ingress resources? 

I think this is a valid ask and has come up in the past, but I just want to confirm your request. =)

**Comment by sudeeptoroy** [comment]
Hi @stevesloka, Thanks for your reply. 
The ask is to support a namespace selector so that contour is not restricted with a finite list of namespaces.

**Comment by youngnick** [comment]
From what I can see @sudeeptoroy, you want to restrict Contour to only looking at a (selected using a namespace selector) limited set of namespaces for all its config, whether it be Ingress or HTTPProxy.

Sadly, I have two problems with this:

Firstly, this is the exact problem that the ingress.class is intended to solve, without needing the additional code support. I understand that there is some additional overhead to your users, but understanding annotations is key to understanding Kubernetes, I don't see how ingress.class is too much here.

Secondly, and far more importantly, adding this capability will require quite a large change to how Contour works. Currently, we use Informers (a client-go construct that helps watching the Kubernetes API), which require a list of namespaces to be specified when they start. They don't support namespace selectors.

So, in psuedo-code, this is how contour serve currently works:
```
start contour
read in arguments and config file
build list of namespaces to watch for things
build informers
start informers
```

Each informer is basically a separate goroutine.

For us to add this functionality, we would need to move to this pattern:
```
start contour
read in arguments and config file
build informer for namespaces
start informer for namespaces
  If namespaces change (because label selector changed, start this whole thing again)
  namespace informer:
    build list of other informers, 
    start list of other informers
```
Each time a label change brought more namespaces into or out of scope, the rest of contour would need to shut down and restart. The pattern of watching resources in a namespace-selected set of namespaces is uncommon because of this problem. Any time there is a namespace labelling change, you need to start the whole controller again to ensure that all the informers are watching the correct things.

Now, none of this means that we would not do this, if the use case was important enough. But given that there is another solution that is the industry standard that's already in use, well tested, and available in Contour, I'm very reluctant to move ahead without more reason.

**Comment by xaleeks** [comment]
I don't think our position has changed here.  I'm going to close it for now.  Feel free to keep engaging the team if you have other related concerns.
