### ISSUE TITLE
Enable gRPC health checks

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2430]
Current active health checks are written for HTTP based endpoints. We should add the capability to enable checking of gRPC endpoints as well.

**Comment by xaleeks** [comment]
Telemetry on gRPC calls is very important for us to be a mature solution.  K8s doesn’t support this natively but grpc itself has a protocol for this.  Can we first define what health or healthy means for our gRPC servers here?  Is it just probing the gRPC endpoints in a contour deployment for basic health status or is it measuring the response for something specific (to Contour).  Is it then up to the user to draw statistics from these responses like total healthy, total unhealthy, etc or can they submit these as a parameter to the probe request somehow

**Comment by youngnick** [comment]
I think what @stevesloka was referring to here was making it so that we can configure *Envoy* active health checking for gRPC backend services. You can do that for HTTP at the moment, but I think that it wouldn't work as expected if you configured an Envoy active HTTP health check on a gRPC service.
