### ISSUE TITLE
Document how to use "projectcontourbuilder"

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2443]
Historically, release container images are pushed to Docker Hub as the user "projectcontourbuilder". We should document that in the release instructions and tell people how to do it. Even better if the release scripts can verify that or do it for us.

**Comment by jpeach** [comment]
I think @youngnick knows about this.

**Comment by youngnick** [comment]
The projectcontourbuilder user is a Docker Hub user that Tim H and I currently have the keys for. This was done to make the 'published by' be a bot, rather than a person. I left how to get the credentials vague because we didn't really have a place to share a credential like that.

Right now, it requires doing a `docker login` as that user from your local machine. I acknowledge this is not ideal.

**Comment by youngnick** [comment]
Now that we are part of the CNCF, we have a few options for sharing credentials securely; I will investigate.

**Comment by youngnick** [comment]
This may be resolved by resolving #3366, since we may not be pushing to dockerhub any more; we'll see what happens there.

**Comment by youngnick** [comment]
This is no longer relevant now we're no longer pushing to Docker Hub.
