### ISSUE TITLE
Ingress class name is not passed to the ingress status updater correctly

### ISSUE THREAD

**Issue by cten** [projectcontour/contour#2481]
**What steps did you take and what happened:**
Didn't use the default namespace (projectcontour), instead it was shortened to "contour".

When using non-default namespace, saw that all ingresses were being skipped by IngressStatusUpdater ie.
`level=debug msg="unmatched ingress class, skip status update" context=IngressStatusUpdater ingress-class=contour-intern
al name=dcp-es-internal namespace=elasticsearch`

**What did you expect to happen:**
Ingress Status field to be updated.

**Anything else you would like to add:**
Can reference slack chat to get more background
https://kubernetes.slack.com/archives/C8XRH2R4J/p1588123185243300

**Environment:**

- Contour version: 1.4.0
- Kubernetes version: (use `kubectl version`): 1.17
- Kubernetes installer & version: kops 1.16.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): debian ?

**Comment by youngnick** [comment]
This is because the value of the `ingress.class` passed down from the `--ingress-class-name` argument to `contour server` is not wired down into the ingress status updater. I'll fix it and see if it's possible to add a test (may not be straightforward because a lot of moving parts that require a Kubernetes API).
