### ISSUE TITLE
Support for running Contour in a single namespace

### ISSUE THREAD

**Issue by josephglanville** [projectcontour/contour#2497]
We would like to deploy independent Contour deployments per namespace. Our use case for this is we have a (set of) multi-tenant clusters with namespaces divided by teams. Each team has a large degree of freedom in which tools they wish to adopt. This is ok for the vast majority of tools which can be deployed in modes that don't require cluster wide access (except maybe an admin to create Custom Resource Definitions).

One of the teams has already adopted Contour and did their best to deploy it in a way that would allow others to but unfortunately they miss-understood the nature of `--root-namespaces`, the problems with which I will describe below.

Currently Contour is designed and only capable of running as a cluster-wide service. It expects to be able to list all of it's managed resources in all namespaces. This requires it to have a ClusterRole with broad permissions. In addition this makes it very impractical to run more than one Contour instance in a cluster because both will be attempting to manage all resources and if they differ in `--root-namespaces` settings will mark each others root `HTTPProxy` objects as invalid.

This cannot be solved with RBAC in the current form as if Contour fails to list resources in all namespaces it will fail to operate correctly.

Our ideal solution would be to deploy Contour + Envoy isolated in each namespace without conflicts from each other with only the CRDs being defined globally, i.e using basic Role instead of ClusterRole.

This feature is already present in the other solution we are looking at, Ambassador: https://www.getambassador.io/docs/latest/topics/running/running/ via it's `AMBASSADOR_SINGLE_NAMESPACE` environment variable and largely inspired my approach in https://github.com/projectcontour/contour/pull/2492 as an attempt to fufil this requirement.

**Comment by stevesloka** [comment]
Hey @josephglanville! This has come up before with similar requirements. One thing you could do today is to add `ingress.class` to your resources. If you set that arg on Contour, it will only watch for ingress resources that match your class. I understand that's not ideal, but might help get through your current needs. 

I think having a flag is good to restrict the surface area that Contour needs to watch but might make it a set of namespaces, rather than a single one. This way we could fit the needs of other users who might need to restrict to a few. 

We do that now with `secrets` when using the `root-namespaces` arg. If you restrict where your roots live, then Contour only watches for secrets in those corresponding namespaces. 

I'd like to see what @youngnick & @jpeach think about this so we can come up with a way to move forward.

**Comment by josephglanville** [comment]
If I am not mistaken `ingress.class` only works with `Ingress` resources. We would like to use the `HTTPProxy` CRDs. I don't believe this annotation is honored on those.

**Comment by josephglanville** [comment]
Using a set of namespaces rather than a single one is possible but does come with caveats. The k8s client informer interface can currently only watch for changes on a single namespace or all namespaces. To implement this more informers will need to be created and started at initialisation.

**Comment by stevesloka** [comment]
> ingress.class only works with Ingress resources

Contour support this on both ingress and HTTPProxy

> k8s client informer interface can currently only watch for changes on a single namespace or all namespaces

Yup, you are correct, what we've done in the past (e.g. secrets for example) is we loop through and create a set of informers that match all the namespaces. We'd just need to replicate that out across the other types (e.g. services, endpoints, etc)

**Comment by josephglanville** [comment]
Ahh I see now it is checked for the CRDs too. This will be an OK workaround for us for now but I would like to proceed with a way to truely filter the namespaces still as that would allow us to not need a `ClusterRole` which is harder to come by in our deployments (we have one for now, hence why we can use the workaround).

**Comment by youngnick** [comment]
So, one of the reasons I asked you to bring this to an issue @josephglanville is that I wanted to talk about selecting namespaces. As part of the work that Contour is doing to support the service-apis, we are going to need to put something in place to be able to watch a label-selected set of namespaces for some resources, so we will have to build that anyway.

I'm currently leaning towards Contour *watching* all namespaces, but only *taking actions* on a set of namespaces. Not much different to now, in terms of actual apiserver events seen, but we would just drop things from namespaces we weren't checking on the floor. That's simpler than starting and restarting Informers whenever the label selection changes. There's obviously still things to be worked out, but a Contour-level setting would be a simpler version of the same functionality.

In addition, I'd like to move away from adding more command line flags, and instead add the functionality to the config file. I'm working on a blog post where I talk about this change a bit more, but I'd like to end up in a place where the only command line flags are ones that are really useful for local development, but *everything* can be configured from the config file.

Does that make sense?

**Comment by youngnick** [comment]
@josephglanville ping - do you have any thoughts on the above? What else do you need here?

**Comment by josephglanville** [comment]
I am not sure I understand what service apis are so it's hard to infer what additional flexibility that entails. However in broad strokes I am generally happy with the idea of making it filter what it acts on. This still requires a ClusterRole however which isn't ideal but will be less brittle than ensuring all Contour objects are annotated to prevent conflicts between controllers.

**Comment by deregtd** [comment]
Seconding the request in this thread.  We're making 6 clusterrole/bindings right now per k8s deployment, with different permissions, because we need a different contour per namespace.  We're using the ingress-class-name parameter selecting for now, just like we were on the nginx ingress controller we had before this, but the cluster-wide model is way more awkward than if it were contained within a namespace.  Limiting both the permission model and the listen model to act only within a namespace (or set of namespaces, I guess, if that's important to someone?) would be vastly preferable, from both a cleanliness and a performance standpoint.  Our current setup has all 6 ingress controllers listening and handling changes to the other 5 namespaces, then ignoring it when it realizes that the ingress-class isn't for it.

**Comment by josephglanville** [comment]
We have settled on a model that uses a single ClusterRole that provides read access to all the resources Contour needs to discover/read, along with a per-deployment Role that grants write access within the specific namespace. Thus the ClusterRole is shared across deployments and does eliminate some of the problems but creating the bindings still requires cluster administrator involvement which is less than ideal for us. The ideal solution would be something that only require the CRD(s) to be created by a cluster administrator and all other resources be able to be created fully namespaced.
