### ISSUE TITLE
[security] Upgrade to Envoy 1.14.2

### ISSUE THREAD

**Issue by pims** [projectcontour/contour#2579]
Due to CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11080 upgrading to Envoy 1.14.2 is recommended.

https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.14.2

Happy to submit a PR if you’d like.

**Comment by jpeach** [comment]
Yup, there will be  new security release soon. @pims if you would like to be the release manager for this, I'd be glad to shepherd that!

**Comment by pims** [comment]
@jpeach I’d love to!

**Comment by jpeach** [comment]
> On 13 Jun 2020, at 12:27 pm, Tim Bart <notifications@github.com> wrote:
> 
> 
> @jpeach I’d love to!

Cool, ping me on Kubernetes slack.

**Comment by jpeach** [comment]
Steps we need to do to make a 1.5.1 release:

- Update the envoy image version on master
- Update the envoy image version on the release-1.5 branch
- Update hack/release/prepare-release.go to optionally take an OLDVERS NEWVERS arguments so that we can cut the 1.5.0 docs across to 1.5.1

Then we can:

- cut the 1.5.1 tag
- push the 1.5.1 Docker image
- create and update GitHub release notes

Then, various docs updates (on master):
- https://github.com/projectcontour/contour/blob/master/site/_resources/envoy.md
- https://github.com/projectcontour/contour/blob/master/site/_resources/upgrading.md

The release process is documented [here](https://projectcontour.io/resources/release-process/), so if you find any inaccuracies we can correct them as we go.

**Comment by pims** [comment]
`1.5.1` is out: https://github.com/projectcontour/contour/releases/tag/v1.5.1
