### ISSUE TITLE
Misleading Proxy status for secrets type opaque

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2616]
If a user creates a secret type `opaque` and references that via a Proxy, the resulting status will say the proxy is invalid because the secret does not exist when it actually does. 

The problem is Contour assumes any tls secret to be type `kubernetes.io/tls`, so when it finds a secret type `Opaque` it assumes it should only contain a `ca.crt` (https://github.com/projectcontour/contour/blob/master/internal/dag/secret.go#L57). When it doesn't, then the secret is not added to the internal k8s cache and further lookups cannot find it which results in the current error. 

This is misleading to users since the secret does exist, just not in the format that Contour would like.

**Comment by jpeach** [comment]
There are multiple secret validation criteria
- `isValidSecret` determines whether a secret will enter the cache
- `validSecret` determines whether a cached TLS cert secret can be used
- `validSecret ` determines whether a cached CA cert secret can be used

The error from `isValidSecret` is logged but otherwise doesn't show up on status. The status error shown to users is due to the failure of `validSecret` and `validSecret`, which is often "no secret found", because the validation failure causes the secret to not ender the cache.

**Comment by stevesloka** [comment]
The user feedback shouldn't be "secret not found", it needs to reflect the actual state which is "not configured properly" or something. We can't depend on a log message in Contour to reflect this state.

**Comment by jpeach** [comment]
> On Jul 9, 2020, at 4:30 AM, Steve Sloka <notifications@github.com> wrote:
> 
> The user feedback shouldn't be "secret not found", it needs to reflect the actual state which is "not configured properly" or something. We can't depend on a log message in Contour to reflect this state.

Right, I’m 100% in agreement with that :)
