### ISSUE TITLE
Enable TCP keepalive on listener sockets

### ISSUE THREAD

**Issue by erwbgy** [projectcontour/contour#2633]
Contour should configure TCP keepalives for Envoy listener sockets so that half-open connections with clients (downstream in Envoy speak) are flushed. This helps Envoy work better with overlay networks which drop long running idle TCP connections. TCP keepalives are already enabled for server (upstream) and xDS connections so this would complete the set.

I have a pull request that implements this by adding SocketOptions if you're open to this change.

**Comment by youngnick** [comment]
Hi @erwbgy, that sounds great. I'm a little disappointed that none of us noticed it sooner!

I guess the only question I would have is if any of us can think of a reason why keepalives would be disabled? If we could, then we should add a way to do it. However, I can't think of any reason to disable it off the top of my head, especially since we've got greater timeout configurability on the way.

Please send through your PR, can you make sure you check CONTRIBUTING.md for commit message style and other stuff? Thanks.

**Comment by erwbgy** [comment]
@jpeach For documenting this change I was thinking that https://projectcontour.io/resources/envoy/ should be updated with a TCP Keepalive section at the end describing what they, noting that they're enabled by default for listener sockets and what the settings are. If that sounds okay I'll create a PR.

**Comment by jpeach** [comment]
> @jpeach For documenting this change I was thinking that https://projectcontour.io/resources/envoy/ should be updated with a TCP Keepalive section at the end describing what they, noting that they're enabled by default for listener sockets and what the settings are. If that sounds okay I'll create a PR.

I don't think that's the right place for this information. The current envoy page is supposed to document Envoy versioning, whereas this information is about configuration and deployment behavior, which is quite a different topic.

**Comment by erwbgy** [comment]
Do you have a suggestion for a different place to document this change then?

**Comment by jpeach** [comment]
> Do you have a suggestion for a different place to document this change then?

Unfortunately I don't see a good place for this in the current docs structure. Let's capture the test in an issue and we can revisit it in the future.
