### ISSUE TITLE
Generate Contour CRDs with V1 CustomResourceDefinition.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/contour#2678]
Generating CRDs as  v1 CustomResourceDefinition resources enables better CRD validation and defaulting, as well as the ability to use `kubectl explain`.

This requires Kubernetes 1.16 or later. We can do this as the default YAML, but we can also generate different sets of YAML (as demonstrated in #2474).

This issue tracks the decision for adding this, and we can also use it to collect other issues that are blocked on the CRD support.

**Comment by skriss** [comment]
A few notes here:
- personally, I don't think we need to generate both `v1` and `v1beta1` CRD YAML -- Kubernetes 1.16 (where CRDs moved to GA) has been out for a year, and folks can always pull an older release of Contour if they really need pre-1.16 support. Moving to generating **just** `v1` CRDs is a lot simpler. Would like to get agreement from other maintainers on this, though.
- currently, our CRDs have `spec.preserveUnknownFields` set to `true`, because they're created as `v1beta1` CRDs and that's the default value for that field in that version. We need to set that to `false` (which is the `v1` default) because (a) we want the behavior of pruning unknown fields, and (b) it needs to be false to make `kubectl explain` work, apparently. Unfortunately, `controller-gen` doesn't seem to allow you to explicitly set it to `false` when generating `v1` CRD YAML, so we'll need users to manually run a `kubectl patch` command to remove that field as part of the upgrade process. It won't be an issue on a fresh install of Contour using `v1` CRD YAML, though, since `false` is the default.

Otherwise, this looks to be a pretty simple change that will add a lot of value going forward.

**Comment by youngnick** [comment]
I'm fine with only outputting the CRD `v1` objects, as you say, I think 1.16 has been out long enough, and this functionality will save all our users a lot of headaches with simple formatting and validation errors.

**Comment by skriss** [comment]
As an update, I was able to add logic to our wrapper CRD generation script to add `spec.preserveUnknownFields: false` to our CRD YAML, so users won't have to do the manual patch.
