### ISSUE TITLE
Is it possible to use istio on top of contour?

### ISSUE THREAD

**Issue by salimuddin87** [projectcontour/contour#2767]
I have a cluster where contour is used as ingress controller. I want to implement Istio on top of that.

should I remove contour and use istio?

OR

Can I use istio on top of contour?

**Comment by youngnick** [comment]
Hi @salimuddin87, thanks for the issue.

Right now, there's not a good way to have Istio and Contour coexist, especially since Istio provides its own Ingress gateway. That's not to say it's not possible, just that none of us have tried it out. (And I personally haven't touched Istio for almost two years).

Ideally, there would be a way to plug Contour in as an ingress controller when using Istio, but I suspect this would need some work firstly to understand how to do that, and secondly to make it work!

Sorry to not be able to give you a better answer. Is there anything else we can help you with in this issue?

**Comment by youngnick** [comment]
Looking over this again, there is another caveat: If you want to join Contour's Envoys to Istio's service mesh, we will need to implement #2883 to enable the Contour Envoys to specify a SPIFFE client cert and complete the mTLS exchange.

xref #2883
