### ISSUE TITLE
CI: Site proof job is running on every PR

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2772]
After the switch to GitHub actions, the site proof job is running on every PR. It really only needs to run when something in the site changes. There's a script to do this check, but it's not working as intended right now.

**Comment by skriss** [comment]
Looks like there are several issues:
- by default, the checkout action only fetches a single commit. our script as written needs history to be able to work. ref. https://github.com/actions/checkout and https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches.
- our script calls `exit 1` if there were no changes to `site/`. this will cause the workflow run to fail, so we need a different way to terminate early. it's probably easiest to just move the files changed check into the siteproof script since that's the only place it's used.
- by default, the checkout action checks out a merge commit for the PR rather than HEAD, so the latest commit won't have `site/` changes (essentially https://github.com/projectcontour/contour/issues/2031 but now on GH Actions)
- if we get it running correctly on PR builds, we're still going to run into https://github.com/projectcontour/contour/issues/2032
