### ISSUE TITLE
Deprecate & remove TLS 1.1

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour#2777]
Reading the docs https://projectcontour.io/docs/v1.7.0/httpproxy/ - TLS section it says

> The TLS Minimum Protocol Version a vhost should negotiate can be specified by setting the spec.virtualhost.tls.minimumProtocolVersion:
> 1.3
> 1.2
> *1.1 (Default)*

I thought TLS 1.1 was deprecated/insecure so I’m surprised it’s the default

More details: https://hacks.mozilla.org/2020/02/its-the-boot-for-tls-1-0-and-tls-1-1/

I guess it would make sense to immediately bump the default to 1.2 and to have a path to remove 1.1

**Comment by dprotaso** [comment]
This is a handy tool - https://ssl-config.mozilla.org/

**Comment by jpeach** [comment]
xref https://github.com/projectcontour/contour/issues/2401

I don't think we should remove this (without a sufficiently log deprecation time), but we should add configuration and flip the defaults.

**Comment by youngnick** [comment]
The 1.1 minimum version is the default for compatibility reasons, currently. I agree that we should change the default to 1.2, and allow 1.1 for a while, with a log indicating that you should stop using it.

This comes under the heading of "people use the proxy as a fixup point", sadly.

**Comment by dprotaso** [comment]
> 
> 
> xref #2401
> 
> I don't think we should remove this (without a sufficiently log deprecation time), but we should add configuration and flip the defaults.


yeah I agree.

**Comment by youngnick** [comment]
Okay, so todo here:
- [ ] Change the default for TLS version to 1.2, with a release note mentioning the current guidance, and noting that we consider support for TLS 1.1 in Contour deprecated and risky, and that it will be removed eventually.
- [ ] Add a startup warning log that using 1.1 is not a good idea and you should use 1.2 if you can.

Wait to see how much community comment there is after this, and set the removal period for TLS 1.1 based on that.

**Comment by youngnick** [comment]
Also, we should note that you can use `MinimumProtocolVersion` to stop the use of 1.1 entirely without it being disabled in Contour itself. Possibly we should default this to 1.2 at some point, as a "removal" step, rather than totally removing the functionality.

**Comment by mattmoor** [comment]
@youngnick does setting that change the defaulting to use that minimum version, or would changing that cause previously valid things to be rejected?

**Comment by youngnick** [comment]
Once you pass the MinimumProtocolVersion, the secure listener will be set to not accept connections from that TLS version. So, clients that try 1.1 will not be able to connect.

Inside Contour, currently, we compare the version to 1.1, and if it's greater use that, otherwise, use 1.1. Implementing this PR would require changing that logic to default to 1.2, and drop down to 1.1 if and only if 1.1 is specified.

This change could possibly be a breaking change for people who require TLS 1.1, as once we change the default, anything using TLS 1.1 will break, and you will need to apply a Contour config change to make your clients work again.

That said, TLS 1.1 was end-of-life on March 30, 2020, so I think we're on reasonably solid ground here - all major browsers support 1.2, so changing the default, possibly breaking people using an end-of-life protocol is acceptable, especially when we will keep the workaround in place for a while as well.

This does not change the TODO list for this issue - still requires the same things, but it will require a release note when it makes it in.

**Comment by skriss** [comment]
I'll start working on this.

**Comment by skriss** [comment]
WDYT about updating both (a) the default for `HTTPProxy.Spec.VirtualHost.TLS.MinimumProtocolVersion`, and (b) the default for the config file's `tls.minimum-protocol-version`, to `1.2` at the same time? It seems easier from a change management perspective so we don't have to spread potentially-breaking changes related to this over multiple releases. This might be what you already had in mind, but I wasn't totally sure from the backscroll.

Changing the HTTPProxy default means that any HTTPProxies (and Ingresses) that did not explicitly specify a value for this field will now default to `1.2`, which *could* break them. The user could fix breaks by explicitly specifying `1.1` where needed.

Changing the config file global minimum default means that any HTTPProxies (and Ingresses) that previously explicitly specified `1.1` will be silently forced to use a minimum of 1.2, which could break them. Again, the user could fix this by explicitly specifying `1.1` as the global min in the config file.

Either way, we'll have to call this out as a potentially-breaking change (if users are relying on TLS 1.1) in the release notes, but if we bump both defaults at once, then it's all in a single release.

**Comment by jpeach** [comment]
The defaulting behavior sounds broken to me. I haven't checked the code but I would expect the config file to have an effect on the proxy objects.

How about adding a warning for use of 1.1 in the 1.9 release, and fixing any issues with the config defaults? That gives operators a chance to notice and remediate before the final change.

Also need to consider that happened for backend TLS.

**Comment by youngnick** [comment]
Yes, I think that adding a warning first is probably a good idea.

However, when we do remove, (that is, in 1.10), I think it should be like this:
- If you're not specifying a version, you get the HTTPProxy default, which should now be tls 1.2. This is probably fine, as almost everything should support tls 1.2 now. If something doesn't work, you can set it back to tls 1.1.
- I agree that we should update the minimum version default at the same time, but we need to ensure we have documentation on what to do if you really need tls 1.1.
- We'll also need to change the HTTPProxy processor behavior such that tls version below the minimum renders the proxy invalid - that at least will supply some feedback to users about what's happening, rather than silently upgrading to tls 1.2.

**Comment by skriss** [comment]
Tasks:
- [ ] (1.10) change the default MinimumTLSVersion for HTTPProxies/Ingresses to 1.2 (#3007)
- [ ] (1.10) add warnings for HTTPProxies/Ingresses that are explicitly using 1.1
- [ ] (1.10?) mark proxies invalid if they request a MinimumTLSVersion that's below the global minimum allowed TLS version
- [ ] (1.11+) change the global minimum allowed TLS version default to 1.2

**Comment by skriss** [comment]
Per https://github.com/projectcontour/contour/issues/2880#issuecomment-756037197, it looks like we inadvertently did a hard drop of TLS 1.1 in Contour 1.11; it's automatically upgraded to 1.2 even if 1.1 is specified. Additionally, we've dropped or are dropping support for most (all?) TLS 1.1-compatible cipher suites, so even if Contour allowed 1.1 to be configured, it likely would not work.

Are we comfortable at this point just officially doing a hard drop of TLS 1.1?

**Comment by dprotaso** [comment]
I'll close this off then and if someone has issues can ping the thread to re-open.

**Comment by youngnick** [comment]
We were always planning on a hard drop eventually, I think that in this case, we should just update all the docs to remove references to it and say it's no longer supported, will be automatically upgraded to 1.2.

**Comment by xaleeks** [comment]
@youngnick can we add Abbie (https://github.com/a-mccarthy) to the project so we assign doc-related tasks to her

**Comment by youngnick** [comment]
@xaleeks Done, I'll create a new issue to cover fixing the docs.
