### ISSUE TITLE
Add support for forwarding of client certificate material to pod (xfcc in Envoy)

### ISSUE THREAD

**Issue by moderation** [projectcontour/contour#2885]
https://github.com/projectcontour/contour/issues/1090 references this functionality but the issue was closed with merged support for client cert validation at Contour only.

NGINX implements this functionality with the annotation `nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream`

We have teams using this annotation with NGINX to perform mTLS with the certificate material upstream at the pod in a k8s cluster.

The xfcc functionality in Envoy is documented at https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert

Following a community call I chatted with @tsaarni who went as far as providing a rough draft of the Contour code required and tested it:

```diff
--git a/internal/envoy/listener.go b/internal/envoy/listener.go
index 4a2f8111..c987536b 100644
--- a/internal/envoy/listener.go
+++ b/internal/envoy/listener.go
@@ -275,6 +275,11 @@ func (b *httpConnectionManagerBuilder) Get() *envoy_api_v2_listener.Filter {
                RequestTimeout:    envoyTimeout(b.requestTimeout),
                StreamIdleTimeout: envoyTimeout(b.streamIdleTimeout),
                DrainTimeout:      envoyTimeout(b.connectionShutdownGracePeriod),
+
+               ForwardClientCertDetails: http.HttpConnectionManager_SANITIZE_SET,
+               SetCurrentClientCertDetails: &http.HttpConnectionManager_SetCurrentClientCertDetails{
+                       Cert: true,
+               },
        }        // Max connection duration is infinite/disabled by default in Envoy, so if the timeout setting
```
However it probably doesn't make sense to send the cert material all the time as it can get quite large and there are bandwidth and message size implications. Ideally this would be exposed as either a HTTPProxy config option or enabled with a Service annotation.

**Comment by youngnick** [comment]
Just to add to @jpeach's labels, I think this is a reasonable request, that will just require some product thought about where we put it in terms of config.

**Comment by jpeach** [comment]
For anyone who would like to tackle this, here's the API I would recommend:
```
--- apis/projectcontour/v1/httpproxy.go
+++ apis/projectcontour/v1/httpproxy.go
@@ -242,6 +242,8 @@ type TLS struct {
        // EnableFallbackCertificate defines if the vhost should allow a default certificate to
        // be applied which handles all requests which don't match the SNI defined in this vhost.
        EnableFallbackCertificate bool `json:"enableFallbackCertificate,omitempty"`
+
+       ForwardClientCertificate bool `json:"forwardClientCertificate,omitempty"`
 }
```

**Comment by tsaarni** [comment]
Another option could be to put it inside `ClientValidation` parameter, in `DowntreamValidation` structure. 

When the client certificate is forwarded, at least proof-of-possession of the private key associated to the forwarded certificate must have been done by Envoy, since backend cannot do it.  It may make sense to do also validation against CA certificate, though doing that in backend is possible if whole chain is sent as well.  

I'm not 100% sure what happens if client would send an unsolicited client certificate when Envoy did not request client authentication i.e. when `ClientValidation` was not configured?  Would XFCC be used without `ClientValidation`?  Likely proof-of-possession check is done by the TLS implementation regardless client authentication being requested or not.

**Comment by jpeach** [comment]
The reason I suggested a flag in the TLS field rather than in the validation is so we can decouple those concerns. It seems reasonable to just ask for a client certificate, forward it to the upstream in a header and let the upstream figure out what (if anything to do with that). This gives a lot of flexibility to the application.

Some sites will also want to validate the client certificates at the proxy or make a validation guarantee. It's probably worth thinking about whether we should publish a header with validation results too.

**Comment by jroper** [comment]
Is this a feature that would likely be accepted if a PR was submitted?

**Comment by enj** [comment]
I spoke with @youngnick and @tsaarni on [slack](https://kubernetes.slack.com/archives/C8XRH2R4J/p1634135970215800?thread_ts=1633876912.202200&cid=C8XRH2R4J) in regards to my initial [implementation](https://github.com/projectcontour/contour/compare/main...enj:enj/f/xfcc).  The feedback was positive.  I have not had a chance to get back to this, but that branch has the core implementation and really only need tests and docs (envoy itself already does all of the hard work - all we need to do is wire up the config through contour - see #3611 as an example of the remaining work).

@jroper feel free to work on this.  It may be a little while before I get back to it.

**Comment by jroper** [comment]
Good to know. We would like this feature at some point in the future (when our product manager prioritises the feature that depends on it), but we don't need it just yet. If when we do need it, it's still not implemented, we'll contribute then.

**Comment by sunjayBhatia** [comment]
@enj @jroper are you still interested in contributing on this issue?
