### ISSUE TITLE
Exposing TCP with FQDN for mongodb

### ISSUE THREAD

**Issue by binnythomas-1989** [projectcontour/contour#2922]
Hello Guys,

Kubernetes: 1.17.5
Contour- contour:v1.8.1

Im aware that we can expose TCP port on Contour using the below link
https://github.com/projectcontour/contour/blob/main/site/docs/main/httpproxy.md#tls-termination-at-the-edge

Is it possible say to expose the port 27017 which is a default mongo db port by the haproxy resource on fqdn.

On implementation of the link, im able to access the port as follows

mongo --host virtualhost:443 -tls

I would like to access it with Virtualhost:27017

**Comment by youngnick** [comment]
The way this can be done, is that you specify that all secure (HTTPS or TLS) traffic is served out of port 27017 for that Contour installation. Then, any requests to the set of Envoys Contour controls will need to arrive at 27017 instead of 443. You can't run 443 TLS and 27017 tls at the same time in Contour right now.

To do that, you need to pass the _Contour_ deployment the command-line flag `--envoy-service-https-port=27017`. In the example deployment, this is set to 443.

To say this another way, Contour is capable of listening on two ports, an insecure one (80 in the example deployment) and a secure one (443 in the example deployment). Only the secure port will do SNI routing, and you can change it to whatever you want. That means, however, that you can no longer use that same Contour install for HTTPS serving.

**Comment by binnythomas-1989** [comment]
Since the contour runs as a Daemonset could we just use it for one tcp scenario?

So how I worked around it is like this.
```
xxx macos-signing-ansible (master) $ kubectl get svc -n projectcontour
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                      AGE
contour   ClusterIP      172.26.45.185   <none>          8001/TCP                                     4d11h
envoy     LoadBalancer   172.26.35.226   xx.xxx.xx.xxx   80:31032/TCP,443:31458/TCP,27017:30194/TCP   4d11h
xx macos-signing-ansible (master) $ 
````
I have created another listener  to point 27017 to 443. In this case would I be able to do tcp and 443?

**Comment by youngnick** [comment]
Contour runs as a Deployment in the example YAMLs, Envoy runs as a Daemonset. You can absolutely use a single Contour-Envoy pair for the 27017 use case, but yeah, that does not seem ideal.

Sorry, I'm not sure what you mean with your workaround, do you mean that you've manually added another listener in your Envoy config? That wouldn't work because Contour won't wire routes to the other listener.

If you've done some sort of port-forwarding thing, forwarding 27017 to 443, I guess that might work, maybe. I wouldn't recommend something like that though.

**Comment by binnythomas-1989** [comment]
I'm just trying to understand a scenario where I deploy jenkins on k8s where I use contour as the ingress class. I would need to expose the following ports 80/443 (http/https) + 50000 (tcp). How would we achieve both using Contour. Another issue is external-dns integration I have seen a merge I think the later release would solve external-dns integrations with http-proxy I presume.

**Comment by youngnick** [comment]
As things stand, in order to be able to expose 80, 443, _and_ 50000, you would need to run two Contour installs and two sets of Envoys. The first would be a regular set, which exposes HTTP/HTTPS, and the second would set either the insecure or secure port to 50000, based on whether the port 50000 traffic does SNI routing or not. Contour can currently only expose two TCP ports per install.

External-dns does have support for HTTPProxy, in its main branch at least, I'm not sure if there's been a release as yet.

**Comment by stevesloka** [comment]
To follow up on this request @binnythomas-1989, are you asking to have the port `27017` be exposed without TLS?

If Contour could give you another port as mentioned in #3263 you'd still need to connect this way:

```
mongo --host virtualhost:27017 -tls
```

Just wanting to confirm your request before digging into what Contour can/can't do today or in the future so we better understand. =)

**Comment by skriss** [comment]
We are working on supporting this via Gateway API, please track #4960, #5160 and #5321 for further updates!
