### ISSUE TITLE
gatekeeper: Validate configuration file configmap

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#2924]
Follow up to #2742, we should also setup some example configs to validate the Configuration file parameters. Currently, if they are configured incorrectly, Contour will just crash. This is helpful to know something is wrong, but we could do better with the validation bits up front.

**Comment by jpeach** [comment]
Another approach is to move the config into a CRD to take advantage of CRD validation as well. This might be useful for service APIs too.

**Comment by stevesloka** [comment]
![image](https://user-images.githubusercontent.com/1048184/93776848-07d0c000-fbf2-11ea-8817-8fb79cf9b1e0.png)

**Comment by youngnick** [comment]
The way I see it, our two options are:
- maintain a YAML-in-YAML configmap configuration, and use an external controller (gatekeeper) to validate that the YAML-in-YAML is valid. This seems complicated, and a lot of overhead to get something that should be reasonably straightforward.
- move towards having our own CRD that directly represents the config options. This does not mean that we drop the YAML config straight up front, but that we would move the parsing to be done into a CRD struct instead of an internal Contour one. The apiserver can already do field-based validation of CRDs, why painstakingly rebuild that a field at a time in Gatekeeper?
