### ISSUE TITLE
Config to modify the request header size

### ISSUE THREAD

**Issue by PrakashArumugamVmware** [projectcontour/contour#2951]
Envoy has a config as part of HTTP connection manager `max_request_headers_kb` to increase the request header size. Contour does not support changing the request header size dynamically.

It would be helpful, if contour could expose a configuration to change the request header size. 

Release slack conversation, I had with @stevesloka  https://kubernetes.slack.com/archives/C8XRH2R4J/p1589385769023800.

**Comment by jpeach** [comment]
Discussed on slack https://kubernetes.slack.com/archives/C8XRH2R4J/p1604352906465900

The issue with the service turned out to not be the Envoy limit, but a problem with Node.Js server returning 431 if header size is greater than 8KiB.

**Comment by youngnick** [comment]
@jpeach - do you think we should still proceed with this issue?

**Comment by BerGer23** [comment]
@jpeach this question just came up for me. Did anything change in the meantime? 
Could not find mention of this in the Contour docs.

**Comment by skriss** [comment]
@BerGer23 Contour has not added a config option for this, as it has not been needed thus far. If you have a need for this, though, I think we would accept a PR for it. Let me know if you are interested in working on it and we can point you in the right direction.

**Comment by derekmceachern** [comment]
I know this has been closed as not planned but I've just come across this and have the need to increase the max_request_headers_kb. Is this still not possible with Contour?

**Comment by tsaarni** [comment]
It is still not possible. Are you seeing problems and is it related to CVE-2026-47774?

**Comment by derekmceachern** [comment]
We are seeing problems but it's not related to the CVE. Thanks for pointing that out as well, I wasn't aware of this CVE.

Our users have some commercial app that is apparently stuffing a bunch of information in the headers and it is larger than the default size. The vendor has apparently asked for an increase in the header size which is why I was investigating if it was possible.

At this point we are considering standing up a plain LoadBalancer IP and bypassing Contour and see if that fixes the problem.
