### ISSUE TITLE
Update ImagePullPolicy

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour#2994]
**Please describe the problem you have:**
The current [reference deployment](https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml) uses `imagePullPolicy: Always` to always pull images. Does a technical reason exist for using `Always` over the default of `IfNotPresent`? If not, I suggest updating the the reference to `IfNotPresent`.

/cc @jpeach @Miciah

**Comment by skriss** [comment]
FYI the rendered manifest (i.e. the one that we link to on the website -- https://projectcontour.io/quickstart/contour.yaml) changes the image pull policy to `IfNotPresent` (https://github.com/projectcontour/contour/blob/main/examples/render/contour.yaml#L1696) -- this is done [in this script](https://github.com/projectcontour/contour/blob/main/hack/generate-deployment.sh#L29-L41).

I'd guess it's left as `Always` in the source YAML in the repo since that one uses the `main` tag, which is **not** immutable.

**Comment by jpeach** [comment]
> I'd guess it's left as `Always` in the source YAML in the repo since that one uses the `main` tag, which is **not** immutable.

Yup, see discussion in https://github.com/projectcontour/contour/pull/2545

**Comment by danehans** [comment]
https://github.com/projectcontour/contour-operator/pull/33 has been updated to use `IfNotPresent` based on the above feedback.
