### ISSUE TITLE
Support for header hash based load balancer policy

### ISSUE THREAD

**Issue by sonawaneshivraj** [projectcontour/contour#3099]
We have a requirement to load balance gRPC streams by performing a consistent hash over a header value. 

Clients send messages (gRPC) to multiple instances of a service, the message contains a well-known header value (entity_id), the messages for a given entity_id needs to be processed by the same service instance.

With Envoy, this can be achieved via [header hash policy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-header). Is there a way to achieve similar behaviour with Contour?

I don't see this as a currently supported [LoadBalancerPolicy](https://projectcontour.io/docs/v1.9.0/api/#projectcontour.io/v1.LoadBalancerPolicy), is this on the roadmap?

I understand this might be a very specific request and I am happy to give out more information if required.

**Comment by jpeach** [comment]
xref #3044

**Comment by youngnick** [comment]
Sorry about the delay in getting back to you @sonawaneshivraj, as @jpeach mentioned, I'd encourage you to take a look at #3044 to see if that level of flexibility would provide what you need (I suspect it would).

In an ideal world, how would you want to configure this?

**Comment by sonawaneshivraj** [comment]
@youngnick, not sure #3044 covers our requirement. I believe #3044 talks in general about a  richer set of load-balancing functionality and the ability to set additional rules. It does not specifically mention the support for header hash-based load balancing. 

I will get back with the details of how we foresee the configuration for this.

**Comment by youngnick** [comment]
If we implement #3044, then as you can see in the examples, that means that you would be able to specify a header hash policy, amongst the rest. In terms of configuration, I don't mean that I need a fully specced out YAML, I meant - what fields would you like to see? Presumably you would need a field to configure which header to use, but would you want anything else?

**Comment by youngnick** [comment]
After having a conversation about this, I think we came up with the following requirements:
- the gRPC client will be supply the required header as part of the initial request (this means that we don't need Envoy to generate a header value)
- if requests come in without that initial request, then the request will be randomly assigned to a backend.

I *believe* we should be able to do this with a relatively simple hash_policy, so it's probably okay to add to our set of shorcuts (similarly to how we have `Cookiee` load balancing now, which is a shortcut for a certain hash_policy).

To do that, we would add a `HeaderHash` value to the `loadBalancerPolicy` field, This would require a way to configure the header to look for, and whatever we do there should be designed with the implemenetation of #3044 in mind (since that will also require a place to put policy-specific configuration). I'd like to avoid a `map[string]interface` field in a struct, but it may be required to be able to do something like this.

Please tell me if I've got any requirements details wrong, @sonawaneshivraj.

**Comment by sonawaneshivraj** [comment]
@youngnick , this is correct.

**Comment by youngnick** [comment]
Assigning @sunjayBhatia as he is going to try and get this one done.

I think the todo list currently looks like this:
- a design for how to add parameters for the `HeaderHash` `loadBalancerPolicy`, which should be a pattern we can reuse for other load balancer policies in the future. (I think that means that a `map[string]interface[]` or `map[string]string` will be required, but if anyone else thinks of another way to do it, I'd love to be wrong).
- an implementation of the `HeaderHash` `loadBalancerPolicy`.

Ideally, we would get this done for the 1.12 release, which is due next week (!). So we don't have any time to spare if we want to get this in. I'm away the next couple of days, but I'm happy with whatever everyone else chooses about representing the config.

Over to you, @sunjayBhatia!

**Comment by sunjayBhatia** [comment]
See https://github.com/projectcontour/contour/pull/3268 for design pass

**Comment by sonawaneshivraj** [comment]
> See #3268 for design pass

@sunjayBhatia , this looks good. Thank You.

**Comment by sunjayBhatia** [comment]
See https://github.com/projectcontour/contour/pull/3282 if you would like to review the changes going in to start supporting this

**Comment by sonawaneshivraj** [comment]
Thank you @sunjayBhatia @youngnick. Will get this tested with our deployment.
