### ISSUE TITLE
Client certificate missing will halt all traffic indefinitely

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [projectcontour/contour#3190]
**What steps did you take and what happened:**
Created a client certificate of type TLS for Envoy to use as Client cert towards the upstream.
Installed Contour 1.10, set the mentioned client certificate in configmap.

Create HTTPProxy object, set up mTLS with the upstream.
Check the proxy is valid, traffic is fine.
kubectl delete <Client cert for envoy>
Check: Proxy invalid (missing secret error message, understandable it is not there), no traffic (of any kind)
Kubectl create <Client cert for envoy> (the same data actually) 
Check: Proxy still invalid (missing secret error message still), no traffic (of any kind)

Other than this certificate rotation works, if secret is overwritten and not removed.

This situation is kept until something triggers reevaluation e.g: removal or addition of httpproxy, removal or addition of service

**What did you expect to happen:**
I would expect things to go back to normal automatically when a missing certificate is reintroduced.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Normal rotation works.

The same happens if the secret is not deleted but not there when Contour 1.10 is installed.
Contour installed with secret missing.
httpproxy added 
(no traffic)
secret added 
(still no traffic)
httpproxy recreated
(everything is fine)

**Environment:**

- Contour version:  1.10
- Kubernetes version: (use `kubectl version`): 1.15.2
- Kubernetes installer & version: 1.16.2
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by tsaarni** [comment]
Thanks for the bug report!  I will look into this. The problem seems to be that `KubernetesCache.secretTriggersRebuild()` ([link](https://github.com/projectcontour/contour/blob/3a20a55d6fc0ba76a535ee5d4e368d2d6d3dd174/internal/dag/cache.go#L337)) only considers secrets that are referred from `HTTPProxy` and `Ingress` but it does not trigger DAG rebuild for secrets that are referred from config file like the `envoy-client-certificate` and `fallback-certificate`.
