### ISSUE TITLE
logging: Add more logging to shutdown-manager

### ISSUE THREAD

**Issue by youngnick** [projectcontour/contour#3286]
In #3192, we've seen some weird errors that might possibly be related to the shutdown manager. Currently though, there's no way to know what the shutdown manager is doing if something goes wrong. Some more extensive logging behind a `debug` flag would really help with troubleshooting this sort of issue.

At a minimum, I think that the shutdown-manager should log when it gets shutdown for some reason. The logs may not always be lost if the pod restarts, and in the cases they aren't (when something has gone wrong), those logs will be very useful indeed.

**Comment by stevesloka** [comment]
What makes logging more difficult is that this is done inside a `preStop` hook, so most of the logs are contained in the `contour envoy shutdown` command which does the actual execution. These logs aren't stored in the `shutdown-manager` logs since it's called by the kubelet in the preStop event. Events will give a bit of detail, but there are some open issues regarding: https://github.com/kubernetes/kubernetes/issues/25766
