### ISSUE TITLE
Support Envoy filter based on `HttpService`? 

### ISSUE THREAD

**Issue by dotansimha** [projectcontour/contour#3309]
Envoy API v3 supports External Authorization using HTTP service, and not only gRPC based. 

See: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-httpservice 

Is is possible to create a Contour external authorization using this method instead of gRPC? I guess it's just a matter of supporting different syntax and passthough it to Envoy?

Thanks!

**Comment by xaleeks** [comment]
Defer to you guys @youngnick  @stevesloka on priority here.  

To me, it’s not critically important at this moment in time in relation to the rest of the backlog.  IMHO, I’m ok with keeping it open and adding a ‘won’t do’ for now, and then re-evaluate in 6 months time.

**Comment by stevesloka** [comment]
@dotansimha currently Contour only supports the gRPC way to connect External Auth Services into Envoy, however, as you said, it's just some extra code to swap out the way Envoy gets configured. 

@xaleeks Anyone can pick up the work and implement it if they'd like. =) I wouldn't put a "won't do" label on things since the community for sure can pick this up and work on it. 

We only have examples now that use gRPC, but if folks wanted the HTTP version, shouldn't be super hard to implement. Just need to figure out how to make it work with ExtensionService (or deprecate that out and come up with something new to match all the use-cases).

**Comment by youngnick** [comment]
As @stevesloka says, it's not too hard to add in the ability to use a HTTP endpoint rather than a gRPC one if that's really what you want. Personally, the thing I like about gRPC is that it forces you to do some things you probably want to do for security when you are talking about an external authorization service, like enforcing TLS.

I guess I'd ask, what's the usecase? I can see that it's nice to have, but how does having it solve your problem @dotansimha ?

**Comment by dotansimha** [comment]
> As @stevesloka says, it's not too hard to add in the ability to use an HTTP endpoint rather than a gRPC one if that's really what you want. Personally, the thing I like about gRPC is that it forces you to do some things you probably want to do for security when you are talking about an external authorization service, like enforcing TLS.

I think it does make sense.

> I guess I'd ask, what's the use case? I can see that it's nice to have, but how does having it solve your problem @dotansimha ?

My use-case was just experimenting with Contour, I was looking for a way to use existing resources we have for authentication (HTTP) without rewriting it with gRPC. 

I agree that gRPC is great for these use-cases, I just wasn't familiar with that, and had an existing authentication service built with HTTP. 

I thought that for Contour it might be simple to support that because it's already available in Envoy?
