### ISSUE TITLE
Check for GatewayAPI after Contour is running

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3377]
Currently at startup, Contour looks for the GatewayAPIs to exist in the cluster. If they don't then Contour doesn't setup informers to them since there's nothing to inform on. 

However, if someone later on adds the GatewayAPIs and wants to start using them, Contour will never update since the informers are never restarted (Unless Contour is restarted).

**Comment by youngnick** [comment]
I don't know if this is such a good idea, because in order to have this auto-detect, then Contour will need to essentially go back around and restart `contour serve` anyway.

That is, if the service-apis objects are installed in a cluster, Contour will need to reread all the associated objects, check that it has the config correct, and, if anything goes wrong, handle it all without interrupting the rest of its operations.

I really think that something as significant as enabling a new API in a controller is okay to require a restart, and that putting that restart in the control of the controller's operator is better operationally. If I was running a contour installation, the last thing I would want is for something to break because someone installed a new CRD into the cluster. Obviously we would try not to have that happen, but it is a risk, and one that we can mitigate simply by putting the control into the operator's hands rather than trying to make things too magic.

**Comment by stevesloka** [comment]
> ...in order to have this auto-detect, then Contour will need to essentially go back around and restart contour serve anyway.

I think that's fine, if Contour is deployed in multiple replicas, one instance of Contour will restart. Envoy's might reconnect to another instance or just wait a bit (if it comes back online fast enough). 

I just worry that users will try and do something with GatewayAPI, nothing will happen and they have no idea why. This is actually how I came up with this issue, I spent 15 minutes debugging stuff to find out that my controller hadn't been restarted. 

I feel like this is a similar issue to config file changes and restarting Contour.  We can start with some good docs to outline this to folks to make it clear and see how it comes up again.

**Comment by stevesloka** [comment]
> I think that's fine, if Contour is deployed in multiple replicas, one instance of Contour will restart. Envoy's might reconnect to another instance or just wait a bit (if it comes back online fast enough).

I say this but yeah you'd need some coordination to bounce instances of Contour one at a time.

**Comment by youngnick** [comment]
I think having Contour randomly restart because the Gateway APIs CRDs changed is much more risky. Yes I know, they're changing more often at the moment, but I think it's a net loss for the operability of Contour, and goes against the "don't have breaking changes happen automatically" rule. This is the same reason why I'm against automatically restarting Contour if the config file changes, it means that editing an object is the same as restarting the service, which could conceivably end up with Contour being offline. 

I agree that we need to make it clear that if you touch the Gateway APIs CRDs at all, you need to restart Contour, but I don't agree that having Contour restart automatically is a good idea. When I was running Kube clusters, I was adversely affected a number of times by things restarting automatically, and I don't think we should do it without careful consideration.

**Comment by stevesloka** [comment]
There are ways to make this work and not fully restart Contour. But I'll close and we'll see how users adopt the new apis and go from there.
