### ISSUE TITLE
gRPC to gRPC Web

### ISSUE THREAD

**Issue by net-brain** [projectcontour/contour#3418]
I have a gRPC Server written in ASP.NET and want to consume that via gRPC-Web. Currently I'm using the Microsoft gRPC-web Wrapper (https://https://github.com/grpc/grpc-dotnet)  which runs fine locally. When I'm using that behind a Contour httpproxy it fails with an http 426 Reply code.

I would like to run the grpc .net OR would like the envoy ding the Wrapping for gRPC-Web to GRPC. Does anyone knows what to do?

cheers

Lorenz

**Comment by erwbgy** [comment]
The default protocol between Envoy and your Pod is HTTP/1.1 so for GRPC you need to change this to HTTP/2 by setting the the spec.routes.services[].[protocol](https://projectcontour.io/docs/v1.13.0/config/api/#projectcontour.io/v1.Service) field on the HTTPProxy object - for example:
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
...
    services:
    - name: my-grpc-app
      port: 443
      protocol: h2
...
```

Alternatively you can set the projectcontour.io/upstream-protocol.h2 [annotation](https://projectcontour.io/docs/v1.13.0/config/annotations/#contour-specific-service-annotations)  on the Service - for example, assuming the Service port is 443 you could add this annotation to the Service object:
```
projectcontour.io/upstream-protocol.h2: "443"
```

You may need to use `h2c` instead of `h2` if plain HTTP/2 is used instead of HTTP/2 over TLS.

**Comment by skriss** [comment]
Closing this out, feel free to reach out again as needed.
