### ISSUE TITLE
Support autorization for http requests (not only https)

### ISSUE THREAD

**Issue by nnahaliel** [projectcontour/contour#3420]
Currently "Authorization servers can only be attached to HTTPProxy objects that have TLS termination enabled" (https://projectcontour.io/docs/v1.13.0/config/client-authorization/#authorizing-virtual-hosts).

Is there an option to change this?

This limitation forces us to handle TLS termination in contour (instead, for example, at the ALB)

**Comment by skriss** [comment]
@nnahaliel see https://github.com/projectcontour/contour/blob/main/design/external-authorization-design.md#https-only for a discussion of why we decided to implement for TLS-enabled proxies only.

We could revisit that decision, but there are some technical constraints that would need to be resolved in order to do so.

**Comment by skriss** [comment]
This has now been addressed by #4994
