### ISSUE TITLE
websocket return error when contour work with istio with gzip filter

### ISSUE THREAD

**Issue by du2016** [projectcontour/contour#3474]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1. install a websocket svc in k8s with istio 1.8.1,
2. install contour 1.10.1 and config httpproxy to this svc,open and test ,the websocket api will return `Error during WebSocket handshake: Unexpected response code: 503`
3. open envoy debug log mode, log print `transfer encoding not allowed in 1xx or 204` so i set `envoy.reloadable_features.strict_1xx_and_204_response_headers: false`
4. then the websocket api return `A server must not mask any frames that it sends to the client.`,i have test all the filters in use in contour,if i remove `envoy.filters.http.gzip` filter, it will work well

**What did you expect to happen:**

websocket work well

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

before install istio,the svc work well
if i access the svc without contour and with istio install,it work well

I don't know why this happens

**Environment:**

- Contour version: 1.10.1
- Kubernetes version: (use `kubectl version`): v1.17.9
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by youngnick** [comment]
Hi @du2016, sorry about the delay in getting back to you on this one.

We haven't done a lot of checking in how Contour interoperates with Istio, so thanks for investigating.

When you say you removed `envoy.filters.http.gzip`, what do you mean? Did you make a custom build of Contour (since we enable that by default)? Or did you disable it on the Istio side?

**Comment by du2016** [comment]
@youngnick  yes i build contour myself

**Comment by youngnick** [comment]
Thanks @du2016, so you found the problem and it was fixed by removing the GZip filter from Contour altogether? If that's the case, I can see that there's some interplay here between Websockets and connecting to anotherr Envoy before the traffic arrives at the actual service.

In order to fix this, I can see a few options:
- adding a way to globally disable the GZip filter. I don't like this one, personally, as that's going to be a big traffic difference across everything to fix this one issue.
- automatically disabling the GZip filter for just Websocket routes, I don't know if this would be possible because the Websocket routes share the same filter chain as everything else.
- Something else, needs investigation.

I agree that this is a problem but it seems to me like this one will need someone to check out what the tradeoffs are before we can build a fix. Sorry @du2016.

**Comment by du2016** [comment]
@youngnick yes, this problem also may cause by istio's envoy config,we may also need talk about whether contour need adaptation for istio

**Comment by youngnick** [comment]
I've marked this as "needs product", just because we'll need to spend some time determining how best to interact with Istio.

In terms of a quicker fix, I don't think we can easily deliver one, because we'll need to understand if it's the chained Envoys causing the issue, or something else.

So, I definitely think we should fix this, but someone needs to investigate what to do from here.
