### ISSUE TITLE
MaxConnectionPools setting for Envoy

### ISSUE THREAD

**Issue by furdarius** [projectcontour/contour#3484]
Envoy configuration tells us, that [MaxConnections](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-field-config-cluster-v3-circuitbreakers-thresholds-max-connections) is "_The maximum number of connections that Envoy will make to the upstream cluster_".

The problem here is that the actual number of connections is much higher than the value of MaxConnections. [CircuitBreaker docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking) presents the formula `cluster maximum connections + (number of endpoints in a cluster) * (connection pools for the cluster)`

> Envoy will ensure that a host selected by cluster load balancing has at least one connection allocated. This has the implication that the upstream_cx_active count for a cluster may be higher than the cluster maximum connection circuit breaker, with an upper bound of cluster maximum connections + (number of endpoints in a cluster) * (connection pools for the cluster). This bound applies to the sum of connections across all workers threads. 

So, the most impactful parameter is `connection pools for the cluster`, which, by default, is equal to the number of HW threads.

Fleet of Envoys, used as an Ingress LB in k8s, establishes a lot of connections to the upstream pods, even if RPS is not that high. During a deployment process of application, all these connections are reestablished, resulting in Envoy high CPU usage. With this behavior, it's hard to plan the capacity of Envoy's nodes.

Would it be reasonable to add [max_connection_pools](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-field-config-cluster-v3-circuitbreakers-thresholds-max-connection-pools) as configuration parameter in addition to `projectcontour.io/max-connections`, `projectcontour.io/max-requests`, etc? In that case, the upper bound of the number of connections could be predicted much better.

**Comment by youngnick** [comment]
Sorry to take a while to get back to you on this one @furdarius.

This seems like one of those options that might be perilous to change. It seems reasonable to have it tunable, but if we're going to do that, we'd need to know a bit more about why the default for `max_connection_pools` is the number of HW threads, so that we can give guidance about when to change it. I prefer not to add a tunable unless we can give reasons why you would change it away, and what the impacts might be.

Could this cause locality problems if your connection is on a CPU that doesn't have a local connection or something? I'm always worried about NUMA things in these cases. Seems like it needs a little spelunking around Envoy to find out what the story is there is in order.

**Comment by furdarius** [comment]
Thank you for the reply!

For the current Envoy setup, we're using [--concurrency](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency) option, to limit the number of Envoy threads.

Our setup includes 12 instances of Envoy as ingress HTTP LB, each instance of Envoy is launched on the x32 CPU node. So, there are at least `12*32=384` connections per pod - quite a high number in low RPS cases.

Having 1K upstream instances means that there are `384K` outgoing TCP connections from the Envoy fleet, that's why setting `--concurrency` twice lower than the number of HW threads (16 instead of 32) is what we do. Otherwise, even kernel conntrack table usage is quite high, not to mention the amount of reestablished connections during application deployment. 

Speaking of the `max_connection_pools` option, yeah, it worth rechecking twice the behavior of the Envoy during the dynamic reconfiguration.

**Comment by youngnick** [comment]
Thanks @furdarius, that's great information, and I can see why you would want to limit that. I guess the next steps are for the person who picks up this issue to look into why the default is set to the number of hardware threads. We could also conceivably just put the tunable in, but I'm a little reluctant to do that without some understanding of the tradeoffs for Envoy in doing that, rather than limiting the concurrency as you are doing now.
