### ISSUE TITLE
Remove RouteParentStatus from routes if a Gateway no longer allows the route's kind or namespace

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour#3526]
If the selector of a Gateway changes, a set of routes might now not be selected any longer, in that case, the route status should be updated to remove the referenced gateway.

//ref: https://github.com/kubernetes-sigs/gateway-api/issues/591

**Comment by skriss** [comment]
As of v1alpha2, Gateways no longer select routes, it's the other way around. Since each Contour instance corresponds to a single Gateway, Contour currently ensures that each route only has status for that particular Gateway, and any others are dropped.

There's still a related question of what happens if a Gateway's allowed namespaces or allowed route types changes to no longer allow a given route to select it -- should Contour then remove the corresponding RouteParentStatus from that route? Definitely a corner case, but I would say it probably does make sense to remove the RouteParentStatus assuming Contour has permission to do so.
