### ISSUE TITLE
Q: Handling millions of rules

### ISSUE THREAD

**Issue by xpepermint** [projectcontour/contour#3607]
I wonder how contour handles e.g. a million `rules` definitions. Let say my k8s hosts many clients and each client applies its own envoy rules. I imagine that the envoy will become slow because of all the conditions that have to be checked on each request. I could run one enovy instance per client but that would require more server resources. 

What is your opinion/experience on that and how others handle/scale such cases?

**Comment by stevesloka** [comment]
Hey @xpepermint! That would be a lot of objects to deal with and my thought would be that you'd run into k8s scaling issues before you'd have Contour issues due to that many resources. In previous testing we had 5k or so Kubernetes Services/Endpoints along with 5k ingress objects and Contour/Envoy handled that fine. 

The more objects there are, the more time it does take for Contour to get all the objects from the k8s api. Envoy does seem to grow with memory and high number of changes as well. 

A good middle ground might be to use `ingressClass` to create shards in a sense of your Ingress resources if the number of objects did become a problem.

**Comment by xpepermint** [comment]
Thanks @stevesloka for sharing.
