### ISSUE TITLE
HTTP1.1/2 connection getting resets

### ISSUE THREAD

**Issue by kumar-subashp** [projectcontour/contour#3686]
We are using contour 1.12.0 with HTTPProxy CRD resource, and observed that both HTTP2 as well as HTTP1.1 api calls are getting reset after 15 seconds(default), It seems to be related to the keep-alive handling, however no relevant properties found in HTTPProxy resource definition, also verified with timeoutPolicy.idle, but in this case also once idle time reach connection gets reset.

Please suggest how to handle this scenario or guide me just in case missed any properties which is already exists.

envoy :1.16.2
Referred : https://projectcontour.io/docs/main/config/api/

**Comment by youngnick** [comment]
Hi @kumar-subashp, thanks for logging this issue.

Can you tell us more about what's happening on the connections? Are they being terminated 15 seconds after being opened,  after 15 seconds of idle time, or some other 15 second period?

I ask because Envoy has a *lot* of timeouts, with interactions that are not always clear without reading the documentation carefully. That's also useful here, because it means that there may be a timeout we can set to fix your problem.
