### ISSUE TITLE
Allow configuration of ext_authz, global_rate_limit HTTP filter priority

### ISSUE THREAD

**Issue by johanbrandhorst** [projectcontour/contour#3726]
Hi, loving Contour, great work!

We've been using the external authz support with great success and recently investigated taking advantage of the new Global Rate Limiter configuration and discovered that the global rate limit filter is hardcoded to being applied after any external authz filter. This means that using the global rate limiter for DDOS protection is not going to protect the external authorization implementation.

The ext_authz filter is added to the filters in

https://github.com/projectcontour/contour/blob/4c0b72ee9d14fe19eaf835417661b9ffeb9ad4de/internal/xdscache/v3/listener.go#L487

while the global rate limiter is added in

https://github.com/projectcontour/contour/blob/4c0b72ee9d14fe19eaf835417661b9ffeb9ad4de/internal/xdscache/v3/listener.go#L499

Note that `ext_authz` is added after _local_ rate limiting (which is part of `DefaultFilters`):

Naturally it would be _best_ if the user could configure the order of these for their own use case, since it meaningfully impacts the meaning of these filters.

**Comment by youngnick** [comment]
Great catch, thanks @johanbrandhorst! Off the top of my head, it does seem that having rate limiting go first as a default probably makes sense (as you say, to protect the external auth service).

But yes, it also seems reasonable to allow the configuration of this order somehow (since maybe you care more about the auth than the rate-limit or something).

@skriss, any thoughts?

**Comment by xaleeks** [comment]
Thanks for this issue, this is definitely a valid use case.  It was just by way of how we developed these features independently that resulted in this behavior where the request in a typical data plane hits the external auth first to get authenticated, then hit the rate limiter.  For DDOS protection, yes we should allow specifying it the other way around.  

Also, I don’t know if we’ve verified this but if using rate limiting in conjunction with JWT authentication, we should be able to rate limit based on header values that are stored in claims on the JWT.  So that means when a request comes through and the JWT gets verified, it only gets rate limited if the token is validated.  This is in the same vein of hitting rate limiter after the ext auth server.  

Can we consider this for 1.17? I'm tagging it so we can consider a design for it.  cc @skriss

**Comment by xaleeks** [comment]
Thanks Nick for tagging it for 1.18

@skriss hope the requirement is clear, feel free to push it out if there are other more urgent issues.

**Comment by sunjayBhatia** [comment]
Chat from triage:
- explore if we can just choose an order?
- explore if we need to make order configurable per FQDN? (un-authenticated requests to foo.com get a different rate limit than authenticated requests to foo.com)

**Comment by skriss** [comment]
ref. https://docs.solo.io/gloo-edge/master/guides/security/rate_limiting/ -- `rateLimitBeforeAuth`

**Comment by sunjayBhatia** [comment]
Just had a thought: doesn’t the ext auth filter cause envoy to immediately return a response on a request that fails authentication? So if the rate limit filter is behind the auth filter, unauthenticated requests will effectively have no limit? (Maybe besides a local rate limit? Would have to try it out to make sure)

**Comment by xaleeks** [comment]
We should either 1) make the order configurable to the user,  or 2) flip the current order as the default behavior.   The referenced 'ratelimitbeforeauth' flag should be optional and so we still need a sensible default.

Can we put this in v1.20?

**Comment by xaleeks** [comment]
@sunjayBhatia  this is going to depend on our upcoming support for OIDC authN as well but it needs to be able to differentiate between unauthenticated requests and failed authentications.  In the absence of authentication on a route object, it just gets rate limited per usual.

**Comment by skriss** [comment]
Couple notes here:
1. it's easy to move global rate limiting to always happen before extauth
1. it's easy to add a purpose-built knob a la what gloo has, e.g. `rateLimitBeforeAuth` or similar, to allow the user to control the relative order of the extauth vs rate limit filters. It could be either global (in the config file / ContourConfiguration CRD) or per-vhost (only relevant for TLS vhosts since auth only works there).
1. it's trickier to expose a generic filter ordering mechanism, in large part because "envoy filters" are not a concept we really expose to the user -- they're not explicitly specified in the API or config, don't have user-facing names, etc.

The downside to doing just the first and second items from the list above are that it's not extensible -- if we ever have other filters that we want users to have control over relative ordering of, then we'll quickly end up with lots of variables controlling the relative ordering of various pairs of filters which would become very user-unfriendly.

We have had users in the past that are rate limiting differently for authenticated vs unauthenticated users (on the basis of a header), so I don't think just flipping the default behavior without also exposing a knob is a good idea.

I guess I'd probably opt for doing 1 and 2, with a knob to control the relative order in HTTPProxy.Spec.TLS, perhaps as part of the Authorization section, so it can be customized per TLS vhost if needed.

Open to any further input here.

**Comment by johanbrandhorst** [comment]
A simple knob similar to Gloo would be suitable for all the use cases I have in mind (option 2).

**Comment by youngnick** [comment]
I think that we should do 1 and 2 as well, and leave more clever ordering of filters for Gateway API (since it's already built with the idea of a filter chain).

**Comment by skriss** [comment]
Pushing this out to 1.21 to get to consensus on approach.

**Comment by derekperkins** [comment]
Related ordering discussion here about jwt vs ext_auth
https://github.com/projectcontour/contour/issues/4826
