### ISSUE TITLE
The Contour v1.16.0 requires Kubernetes >= v1.19

### ISSUE THREAD

**Issue by takama** [projectcontour/contour#3749]
**What steps did you take and what happened:**
Install the Contor v1.16.0 via helm charts

contour-7c9f75d965-d27tk   0/1     CrashLoopBackOff   1          20s

time="2021-05-28T20:23:23Z" level=**fatal** msg="failed to create informer" error="no matches for networking.k8s.io/v1, Resource=ingresses" resource="networking.k8s.io/v1, Resource=ingresses"

**Anything else you would like to add:**
The ingress `apiVersion: networking.k8s.io/v1`started from the version of Kubernetes [v1.19 ](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource)
To be compatible with Kubernetes <= v1.18 the ingress API version should be `networking.k8s.io/v1beta1`.

**What did you expect to happen:**
Expectedly, it should work with the last stable GKE v1.18 if it was not declared incompatible with Kubernetes <= v1.18

**Environment:**

- Contour version: v1.16.0
- Kubernetes version: (use `kubectl version`): v1.18.17-gke.700
- Kubernetes installer & version: GKE 1.18.17-gke.700
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): COS containerd

**Comment by youngnick** [comment]
Thanks for logging this issue @takama. In general, Contour's Kubernetes version support tracks the supported Kubernetes versions. As you can see from our (compatibility matrix){https://projectcontour.io/resources/compatibility-matrix/], we haven't officially supported Kubernetes 1.18 since Contour 1.14.

However, I one hundred percent acknowledge that we have done a bad job of publicizing both this fact, and the Ingress v1beta1 removal. I will be adding some bits to our standard changelog template:
- We will call out the currently supported Kubernetes versions, and note if that changes.
- We will call out object deprecations like this as a first-level changelog item.

Thanks as well for the note about GKE stable only being 1.18, but since that's out of upstream support, it's out of our support too.

**Comment by takama** [comment]
Thank you @youngnick  for your response
> As you can see from our (compatibility matrix){https://projectcontour.io/resources/compatibility-matrix/], we haven't officially supported Kubernetes 1.18 since Contour 1.14.

Ok, then, please change the message on the page above and [here](https://github.com/projectcontour/contour) that the minimum compatible Kubernetes version now is v1.19. (not v 1.16)
Because it was working on GKE v1.18 with Contour v1.15.1

**Comment by youngnick** [comment]
Yes, that seems quite fair, thanks for pointing those out.

**Comment by sunjayBhatia** [comment]
Made this PR to help clarify: https://github.com/projectcontour/contour/pull/3751

**Comment by xaleeks** [comment]
I think we can close this
