### ISSUE TITLE
Moving the website into its own repository

### ISSUE THREAD

**Issue by OrlinVasilev** [projectcontour/contour#3770]
Based on: https://github.com/cncf/techdocs/blob/main/assessments/0001-contour.md

Moving the website into its own repository
Docs+Code combined repositories are a long-term risk. We strongly recommend decoupling these into their own repositories.

1. Figure out any code-related dependencies, i.e. API documentation that might be autogenerated, and figure out how to decouple this.

2. Create a separate documentation/website repository and move the Netlify configuration & docs code into it.

3. Develop a maintainers list/maintenance plan for the documentation and its repository.

**Comment by youngnick** [comment]
Historically, we had them in the same repo so that it would be easier for a small team to ensure that we kept everything up to date. We could ensure that the docs are in the same PR as the code.

I'll be honest, that I'm not sure we're big enough *yet*, for the separation of docs from code to be worth the additional overhead of requiring separate PRs. I think that I would rather we address this feedback by ensuring that we have good information in CONTRIBUTING.md etc about how to do docs PRs, and that do the other things first. This feels like a future optimization to me.

What are your thoughts @OrlinVasilev?

**Comment by OrlinVasilev** [comment]
I do share the same opinion for now looks like mono-repo is good enough and it's easy to manage when we introduce new features for example with single PR you can fix code and website if needed!

@celestehorgan is that potential risk during the Contour graduation process?

**Comment by stevesloka** [comment]
Seems like consensus is that the single repo as it is today is fine.
