### ISSUE TITLE
session affinity irrespective of backend scaling

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour#3808]
Contour supports cookie based session affinity through setting loadBalancerPolicy strategy: Cookie.  The docs state 

“Session affinity is based on the premise that the backend servers are robust, do not change ordering, or grow and shrink according to load. None of these properties are guaranteed by a Kubernetes cluster and will be visible to applications that rely heavily on session affinity.

Any perturbation in the set of pods backing a service risks redistributing backends around the hash ring.”

I think the behavior should be such that adding pod replicas for the service shouldn’t break any existing affinities.  So it should continue sending requests to the same pod even if it’s getting overloaded.  This is backend scaling and it shouldn’t affect what I think is user defined behavior.  If it’s a limitation due to underlying ring hash, we can leave it as it is for now.

**Comment by youngnick** [comment]
I agree that it would be nice if we could get consistent hashing that didn't break existing affinities, but it turns out that doing that is actually a ridiculously difficult design problem, that no one has got right yet.

In terms of what we can actually do, the available options for Envoy's consistent hashing are ring hash or Maglev, both of which consistently hash by calculating a hash based on some deterministic method (which we can influence using hash_policy, as in #3044 and others), and then distribute that hash across the current backends (ring hash uses a circular ring, where the hash value and server are points on a ring, and the algorithm picks the next server after the hash value, and maglev uses a table method where the table of 65537 entries are divided up between the available backends). See [Envoy's supported load balancer docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers) for some details and links to comp sci papers on the underlying algorithms.

In either available option, changing the backends will necessarily change some of the hashing. Ring hash actually does a reasonably good job, in that it can leave some parts of the ring alone, but in order to improve this, we would need to contribute a new algorithm back to Envoy. There is some interesting work being done in this area, [Github's GLB](https://github.blog/2018-08-08-glb-director-open-source-load-balancer/) and [Cloudflare's Unimog](https://blog.cloudflare.com/unimog-cloudflares-edge-load-balancer/) come to mind, but the specific version of rendezvous hashing used in both those implementations is not available in Envoy yet.

**Comment by xaleeks** [comment]
Thanks Nick, we can leave it alone for now then.

**Comment by sunjayBhatia** [comment]
seems like this is closable

**Comment by youngnick** [comment]
Agreed, I think we should close this one out since it's wontfix.
