### ISSUE TITLE
HTTPProxy validation takes up to 5 minutes

### ISSUE THREAD

**Issue by zkutasi** [projectcontour/contour#3845]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We are installing our company's project into Kubernetes, in our CI, every iteration, many-many times. After helm installation, we load in certificates for ingress access into the proper places, and we wait for the HTTPProxy to become Valid. We experienced up to 5 minutes of delay between the Certs are available in secrets and the HTTPProxy to be Valid which seems off to me. The certs ARE valid, they are usable, just Contour for some reason takes ages to state Valid in the HTTPProxy, and the ingress does not work until that.

**What did you expect to happen:**
I expected this to happen in a few seconds, topmost 1 minute but that also seems an error to me. If in the background all this is event-based, it shall not be so slow.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I observer random time-delays, from 20 seconds up to 5 minutes so far.
Issue is reproducible in a given cluster... but each cluster gives me different times

**Environment:**

- Contour version: 1.15.1
- Kubernetes version: (use `kubectl version`): 1.20.4
- Kubernetes installer & version: Company internal (based on kubeadm)
- Cloud provider or hardware configuration: SLES Pre-provisioned servers
- OS (e.g. from `/etc/os-release`): SLES 15 SP1

I just would like to ask, please give some pointers what to look for: Which component, which log, which command. Also can you perhaps describe for me what contour does in the background to validate, what is the procedure, maybe this helps to figure out where I would need to look? I was trying to look for API-rate-limiting (nope), CPU load (we have 30 vCPU per Node), network issues (nothing I could find), debugging with Contour, Envoy (nothing is showing in the logs). Honestly, not sure even where to look for, what to do to debug.

I have also conducted the following test:
1) installed the product
2) waited for 15 minutes after helm install --wait passed
3) loaded in the certificates.
Now I got just 3 seconds of delay !!! SO this is indeed some rate-limiting, some slowness... but what exactly and how we could speed things up? I could not find anything about what is Contour doing in the background here.

I can not easily give you detailed logs, or detailed info, but I will try to do my best (company policy of course).

**Comment by skriss** [comment]
hey @zkutasi it is definitely not expected to take 5min for HTTPProxies to be processed/marked valid. Could you provide the exact order of operations between bringing up Contour, creating HTTPProxies, and creating the certificate secrets? Also, is it possible for you to (1) [enable debug-level Contour logging](https://projectcontour.io/docs/v1.16.0/troubleshooting/contour-debug-log/); and (2) tail the logs while the certificate secrets are being created, and describe what (if anything) is appearing in the logs at that point?

**Comment by zkutasi** [comment]
Hi,

The exact order is:
1) We install everything in one go: Contour (in HA mode), Envoy, and like 50 other workloads, in total around 650 YAML files, using helm (we also have lots of pre and post install job hooks extra). This also contains our microservices, with their HTTPProxy descriptors
2) We wait until helm --wait says everything is OK, this takes roughly 10-12 minutes now
3) Now the HTTPProxy is invalid, because it reflects to a secret that although exists, is empty (we have an in-house developed microservice that provides secrets based on loaded certificates, and updates secrets instantly when the certificates are loaded)
4) Now we execute our "post installation": Load in those certificates, and trigger the re-generation of those secrets. I can observe that the secrets are full of certificates after 1-2 seconds of the loading of them into the component's database. I have also checked directly on KubeAPI REST interface that those secrets are there in nearly an instant
5) Now we wait for the HTTPProxy to become valid, in order to conduct our tests later we need them, and this Phase takes many minutes now.

I have enabled contour debug logging during installation
[contour_log_1.txt](https://github.com/projectcontour/contour/files/6740330/contour_log_1.txt)
[contour_log_2.txt](https://github.com/projectcontour/contour/files/6740332/contour_log_2.txt)

I have sed-ed out my company stuff, but otherwise they are intact. I enabled --debug and --kubernetes-debug 9 (not sure what is the interval here though, was not able to figure out)

**Comment by skriss** [comment]
@zkutasi thanks for the detailed info. I have gone through a basic attempt at reproducing by setting up an `HTTPProxy` that references an existing, but empty, TLS secret, observing it's marked invalid, then updating the secret to include TLS cert data. Unfortunately this didn't reproduce the issue - the `HTTPProxy` was immediately marked valid once the secret was updated.

I've taken a look through the code and I don't see anything obvious that could be causing the delay. Based on the logs, it seems like maybe the Secret informers are missing events for some reason, since I don't see any evidence that the events are being received and triggering a DAG rebuild, though I'm not sure why that would be the case.

I'll continue digging to see if I can find anything else. We may also need to add some more detailed debug logging to see if we can narrow down what's going on.

**Comment by zkutasi** [comment]
@skriss , Thanks for looking into this. Yes, if I do this after the installation and wait for 10-15 minutes (maybe 5 would be enough, did not check) I also observed instant Validation. This just seem to happen right after installation, which makes our CI pipeline kind of sleeping for 5 minutes... one might way it is OK, but this is not the only sleep we have, and not the last one we will have :).

This is why I am thinking, maybe KubeAPI is overwhelmed, but I do not see any logs in it about the rate limiting... also I have checked KubeAPI with

```
curl -k -X GET $APISERVER/api/v1/namespaces/eric-eea-ns/secrets/xxx --header "Authorization: Bearer $TOKEN" -
-insecure
```
And the updates are there in a few seconds most. Not sure if this is a relevant test though. I have tried to see if I can get some metrics of KubeAPI server like queue size, or some other useful ones, but for me the APIServer has around 30k metrics, whcih I am not gonna find useful at first sight :)

**Comment by youngnick** [comment]
Some quick thoughts before I get to what I think the actual issue is:

@zkutasi I think that checking the APIserver rate-limiting is definitely a good idea. Once thing that I've seen in big, busy clusters before is that the updates that go from the Kubelet back to the apiserver have quite a small default queue size, and if that queue exceeds the size, it will be taildropped. This means that updates will be skipped until either the kubelet does a full state dump or the apiserver polls the kubelet (I can't remember which it is). But it can produce 5-10 minute wait times for many things you might not expect.

Unfortunately, in the case where you are pushing a lot of change to the apiserver reasonably quickly, it is tricky to troubleshoot. As far as Contour is concerned, the way that HTTPProxies are validated is that Contour sees an update to the relevant Secret, then triggers a DAG run, updating its internal data model. This is when the Secret is checked for validity, so theoretically, Contour should see Secret updates as soon as its watchers are informed. However, Contour can only _write that information back_ to the HTTPProxy once it's elected a leader (so that only one Contour is writing to the proxy at any one time.) This shouldn't be blocking the config actually showing up in Envoy, since the status updates are written back to the object by a separate goroutine than the ones that handle Envoy config.

To get to the actual issue though:

I had a look through the logs you sent, and it looks like both of the Contour pods are still having leader elections after 18 minutes. This is *way* too long, and I would expect this to be much shorter.

Can you tell us more about if you configure the leader election parameters? If there are many Contour runs at the same time, or in quick succession, and they all use the same configmap object, then you may get problems around different installs not being able to arrive at a consensus as to who is the leader.

If it is the case that there are lots of installs all using the same configmap, there are a few things you could do:
- ensure that the leader election configmap is separate to the actual configuration configmap. You can actually use an empty configmap, the leader election code uses annotations on the object to actually perform the election.
- If the installs are going into the same namespace, ensure that the election configmaps are distinct per install.
- If the installs are not going into the same namespace, then something else is going on.

**Comment by zkutasi** [comment]
@youngnick 
Thanks for looking into this, I am already lost how to even debug this thing :)

I have re-checked the logs, I can see in 1, that the leader is elected at the start of things, at 10:40:32, where do you see it is still ongoing?
We seem to use a single configmap, for everything related to Contour, I have checked, and now it has the annotation, like this:
```
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"company-ingress-ctrl-traffic-contour-5d7bfb8bf4-x96ck","leaseDurationSeconds":15,"acquireTime":"2021-07-01T09:49:44Z","renewTime":"2021-07-01T09:54:52Z","leaderTransitions":1}'
```

This is our contour config in the Deployment/Pod:
  containers:
  - args:
    - contour
    - serve
    - --incluster
    - '--xds-address=::'
    - '--stats-address=::'
    - --xds-port=8001
    - '--envoy-service-http-address=::'
    - '--envoy-service-https-address=::'
    - --contour-cafile=/ca/ca.pem
    - --contour-cert-file=/certs/tls.crt
    - --contour-key-file=/certs/tls.key
    - --config-path=/config/contour.yaml
    - --ingress-class-name=xxx
    command:
    - /api-reachable.bash


In our CI, we use separate clusters, this cluster I have conducted the tests on, is only mine, nothing else runs on it, as you see we have a huge product in our hands with 650 YAMLs. We have two Contour deployments for supporting traffic separation, both of them have 1-1 configmap, both of them are in high available redundancy. We only use a single namespace, no other namespace has contour in them, the whole cluster is having just as many as I install during the tests.

About the rate-limiting of the API server... I am extremely unfamiliar with the topic, but I have read, that there are some tricks here:
1) https://kubernetes.io/docs/concepts/cluster-administration/flow-control/, we do not have this feature set
2) There are default legacy ways on the apiserver, like --max-requests-inflight and some others, these are not set on our API server config
3) Default seems to be 400 in-parallel requests? But watches are not under rate-limiting at all the documentation says: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

I will try two things now:
1) Reduce the HA of Contour to 1, see if that helps in anything
2) Try to disable the API-server rate-limit, hopefully it will not crash, and see if things are better. I have read that it is only a memory-intensive thing to do this lets see how much. Then I still can fine-tune the rate-limit if this is a success.

**Comment by zkutasi** [comment]
Unfortunately no luck... even if there is one contour per network (non-HA, we still have two distinct contour instances), even if I raise the rate-limit settings to 2000 (0 crashed the API-server for me), the situation is the same.

**Comment by youngnick** [comment]
Sorry for the delay on getting back to you @zkutasi, thanks for the further troubleshooting and info.

You said that you have two Contour installations for traffic separation in the same namespace, do they use separate configmaps for leader election? What I'm thinking here is that if they are fighting for control of the leadership (because the election has two sets of voters that don't agree), then it may take a long time for things to converge. 

I would really recommend if you are running multiple Contour installations, to run them in separate namespaces (one namespace per Contour installation). I can't say for sure if that has any impact here, but a lot of stuff we do assumes that, and that assumption may be a problem.

Thanks for checking the rate-limiting as well, the one I've seen before is actually the *kubelet* rate-limit for updating the apiserver, because when something happens on a node (like a pod being scheduled), the node has to tell the apiserver the status, and it does this by sending an update back to the apiserver. So if you can get the nodes to hold a longer queue, sometimes this sort of weirdness from large bursts of change can get better.

I should be clear though, I'm totally guessing with all of this. The reason I'm pushing on the leader election is that it seems really weird that it takes a long time when the cluster is still in flux vs when it's more stable later. Both leader election and apiserver rate limiting are things I've seen affect that sort of thing before. It could totally be that we have a bug with Contour that is causing this, but without elminating these other things, it will be difficult to get to it.

**Comment by zkutasi** [comment]
@youngnick , thanks for guessing with me :)

Yes, we have two contours in one namespace, each of them has their own ConfigMaps... unfortunately it is part of our design that this big application with 650 YAML files is in one single namespace, as we have many-many restrictions that only applicable to a namespace that has to go with it (mutual TLS is one example). I have also tried to run some experiments with non-HA, where there was two contour instances, each with 1 replica. No difference. I think I also tested in the past a single contour HA instance also. We have our internal Team of course who is responsible for Contour, also an internal Team who is responsible for Kubernetes... I am also trying to get help from them, but so far nothing.

If I can get my hands on a cluster again, I will try to just run one single Contour instance with 1 replica, and see if that still reproduces the issue or not.

Do you have maybe info about how that kubelet rate-limiting works, and how one can set it? I could not find exact info, would try it out as well.

**Comment by zkutasi** [comment]
I think we have found the solution: Contour was CPU limited to 75m CPU, which seems for some reason extremely low and 150m CPU works like a charm... **is there any guidance on your side of the minimum allowed such settings?** I have found also this: https://github.com/kubernetes/kubernetes/issues/67577, which states that there is a nasty CPU Throttling bug in some earlier Kernels and we have SLES 15 SP1 with kernel 4.12, so it might be this one, or maybe 75m CPU is just way too little... but it is strange that simply raising it to 150m CPU solved the issue, and we observer 5-15 seconds delay only, with 1 CPU I observer instant validation.

**Comment by stevesloka** [comment]
This has come up in the past and we need to rerun some of the metrics bits we did before, but so much depends on each cluster environment to come up with generics. 

But glad to see that you've found some success @zkutasi!

**Comment by youngnick** [comment]
Hmm, that is interesting, thanks @zkutasi! My guess on this one would be that, because the CPU scheduler reads fractional CPU usage as "how many time slices to give to a process", on a busy cluster (such as one where you've just added a lot of config), Contour probably just didn't get enough time slices to do all the required operations to update the status.

The status updating uses goroutines for concurrency quite heavily, so it makes sense that it's sensitive to being CPU-starved.

Do you think we should mark this down as "if you see something like this, try increasing your CPU limit for Contour" and close this out?

**Comment by zkutasi** [comment]
Hi, if you could just keep this open for a few days more... our internal Team will try to conduct some tests to verify this, I will try to return to here and report back. But all in all, I think this issue was solved, we are just trying to gather more info to better understand this situation.

**Comment by youngnick** [comment]
No problem, we'll leave this open until you report back.

**Comment by Zsolt-LazarZsolt** [comment]
Hello Everyone.

I was able to collect some traces the following way.

Include a side container beside contour trying for http://127.0.0.1:6060/debug/pprof/trace?seconds=295 with wget. 
Then recreate the contour deployment with this setup, wait for the traces to finish and collect them.
With this I'm not exactly recreating the problem, as this is done after everything else is already installed.
I collected one with cpu limit of 75 and 150 and more. I will have to look into if I can share the exact traces.

Can you get any useful info out from this maybe?
From what I could gather from this and other try runs in my system. 

![trace](https://user-images.githubusercontent.com/50740275/126171922-a5bd878d-58a4-439f-82df-5b6e089f80f0.png)

Contour starts something similar to the following stack trace:

github.com/google/go-cmp/cmp.(*state).compareAny:290
github.com/google/go-cmp/cmp.(*state).compareStruct:427
github.com/google/go-cmp/cmp.(*state).compareAny:286
github.com/google/go-cmp/cmp.(*state).comparePtr:579
github.com/google/go-cmp/cmp.(*state).compareAny:292
github.com/google/go-cmp/cmp.Equal:94
github.com/projectcontour/contour/internal/contour.(*EventHandler).onUpdate:179
github.com/projectcontour/contour/internal/contour.(*EventHandler).run:139
github.com/projectcontour/contour/internal/workgroup.(*Group).Run.func2:95

This takes as long as it takes, and until the whole work finishes (the green lines in the trace), Contour seems to be "blind" to changes coming from the watcher, buffering them(?), and only checking the changes after this work finishes.

Are the internal/contour.(*EventHandler).onUpdate, onDelete, and OnCreate events computed after each other? 
I could guess with all the changes happening to the cluster with the install, all these events creating similar traces and it just takes time to get to the one, that actually making the httpproxy valid. 

My question is. What would be a good way of looking into these time related problems which tool could give usable info?
I could also try pprof. 
Second question:
Can somehow the perceived number of cores be a problem? As far as I see, in these traces, the pod sees as many cpu-s as the worker. 
I was able to set a limit on this with an environment parameter, but I could not try if it has any affect.

**Comment by erwbgy** [comment]
FWIW on busier clusters I have found that using the Vertical Pod Autoscaler to set the resources (particularly CPU) helps with slow HTTPProxy status updates - something like:
```
apiVersion: policy/v1beta1
# Use apiVersion: policy/v1 with k8s >= 1.21
kind: PodDisruptionBudget
metadata:
  name: contour
  labels:
    app: contour
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: contour
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: contour
  labels:
    app: contour
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       contour
  updatePolicy:
    updateMode: "Auto"
```

**Comment by youngnick** [comment]
> Are the internal/contour.(*EventHandler).onUpdate, onDelete, and OnCreate events computed after each other?
> I could guess with all the changes happening to the cluster with the install, all these events creating similar traces and it just takes time to get to the one, that actually making the httpproxy valid.

Yes, those events are all sent down a single channel, so they're serialized. So, when there are a lot of changes, Contour will have to drain all the pending watch updates before getting to the one that renders the HTTPproxy valid. I think that changing this too much is risky because of races around the eventual consistency of the Kubernetes objects as a whole.

Given the single-channel structure, I think that having more cores or more CPU time available will both help in so far as it helps the EventHandler process updates more quickly. I don't think there's any way to safely skip object updates without checking to see if they are relevant (which is what the EventHandler is doing anyway).

**Comment by erwbgy** [comment]
> Given the single-channel structure, I think that having more cores or more CPU time available will both help in so far as it helps the EventHandler process updates more quickly. 

Our experience agrees with this.  We found that more CPU for the contour Pods is required when there are lots of HTTPProxy objects and lots of churn - for example 5.5 cores with 5 replicas on a multi-tenant cluster with 3000+ HTTPProxy objects.  Even then we sometimes see that is takes more than 3 minutes for an HTTPProxy object to become valid.
