### ISSUE TITLE
Add support "Local reply modification"

### ISSUE THREAD

**Issue by VA-PLE** [projectcontour/contour#3883]
Hi there. I tested the contour in our kubernetes cluster, it works great. But the specifics of our application requires a function to change the status codes. In envoy it is implemented and works well https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply. I would like to see this feature in the contour.

**Comment by youngnick** [comment]
Thanks @VA-PLE. can you tell us more about this feature? What use case do you want to solve? Is it something that we can solve automatically for you?

**Comment by ploddi** [comment]
Hi there. I'm working in same team with @VA-PLE. We have following use case: we have to override code and body of `50x` responses from application, and send them back to client as `200 OK` empty body responses. Is there way to configure such setup?

**Comment by youngnick** [comment]
There is not currently, no. In order to build this, we'll need to come up with a design and then build it out. We've already got #1627 to enable 301/302 redirects, this seems like it will be a reasonably similar functionality. I've marked this to be triaged and prioritized, so we will definitely see what we can do.

**Comment by VA-PLE** [comment]
OK, thanks. If that helps, here's how to setup "Local reply modification" info https://github.com/envoyproxy/envoy/issues/14203#issuecomment-735739390
