### ISSUE TITLE
Envoy 1.19 is unable to communicate with downstream Dotnet gRPC service over h2c

### ISSUE THREAD

**Issue by bourquep** [projectcontour/contour#3940]
**What steps did you take and what happened:**
After upgrading from Contour 1.10 to 1.18 (which ships with Envoy 1.19), my grpc-web clients are unable to talk with a Dotnet grpc service.

Envoy logs:

```
upstream reset: reset reason: remote reset, transport failure reason:
```

Dotnet logs:

```
HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The request :scheme header 'https' does not match the transport scheme 'http'
```

This is very similar to this Istio issue: https://github.com/istio/istio/issues/34448

**What did you expect to happen:**

Contour/envoy should still allow me to connect to downstream gRPC services over h2c.

**Anything else you would like to add:**

```
grpc-web client -- https --> Envoy -- gRPC h2c --> Dotnet 5 service
```

**Environment:**

- Contour version: 1.18
- Kubernetes version: (use `kubectl version`): v1.20.8-gke.900
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`):

**Comment by bourquep** [comment]
After a bit of digging, this problem was actually introduced in [Envoy 1.18](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.18.0):

> http: fixing a standards compliance issue with :scheme. The :scheme header sent upstream is now based on the original URL scheme, rather than set based on the security of the upstream connection. This behavior can be temporarily reverted by setting envoy.reloadable_features.preserve_downstream_scheme to false.

The problem with this is that Dotnet Kestrel refuses any connections whose `:scheme` header doesn't match the actual underlying transport.

Because it is Envoy that terminates the public SSL connections, and it communicates to my service via `h2c`, it should not set the `scheme` header to `https`.

I could revert to the "old, working way" by setting `envoy.reloadable_features.preserve_downstream_scheme` to false, but I am not sure how to do this... There is nothing in the documentation that mentions how we can customize the Envoy config.

**Comment by youngnick** [comment]
Sorry for the delay on responding to this one @bourquep.

It seems like you would like a way to set `envoy.reloadable_features.preserve_downstream_scheme` to false somehow by Contour?

This sounds like it should be okay, we would need to check the details to see if there are any other implications, and we would probably want to start with a Contour-global setting rather than a host-specific one. Do you think that would be acceptable? (Obviously, pending investigation and other maintainer agreement)

**Comment by bourquep** [comment]
@youngnick Indeed, as far as I can tell by my research, setting `envoy.reloadable_features.preserve_downstream_scheme` to `false` would fix the problem with Kestrel. All I need from Contour is a way to configure this 😄. 

In my personal use cases, a Contour-global setting would work as my services are all written in .Net. But I could imaging that having a per-route setting could be useful to those who have services implemented in a variety of languages.

**Comment by youngnick** [comment]
I've dropped this onto our board for prioritization.

**Comment by davidovich** [comment]
We are affected by this issue also. Since we set `hc2` at Contour HTTPProxy configuration to allow clear text HTTP/2 and that TLS is terminated at envoy, is there a way to set the scheme to `http` ?

As this change in Envoy seems to enforce the standard, I do not understand how passing the original scheme is meant to work with `h2c` as clearly the upstream cannot use the `https` scheme if TLS is already terminated at Envoy.

**Comment by davidovich** [comment]
Note that this issue seems only to affect .NET core and [version 6 should provide](https://github.com/dotnet/aspnetcore/pull/34013) a setting to fix this issue.
