### ISSUE TITLE
Alternatives approaches to supporting ExternalName services 

### ISSUE THREAD

**Issue by dprotaso** [projectcontour/contour#3950]
### Problem

The `enableExternalNameService` config being defaulted to `false` is a breaking change for users 

Now that there is a PR mitigating envoy admin console access - https://github.com/projectcontour/contour/pull/3934 we should consider alternatives/modifications to that flag.

https://github.com/projectcontour/contour/blob/f9f263e96668437a4f1c33ab7aa7d2be9aeb3d69/examples/contour/01-contour-config.yaml#L53-L57

#### 1. Remove the flag

By removing the flag we would defer the responsibility of _who_ can create `ExternalName` services to a separate system - ie. https://www.openpolicyagent.org.

This would fall on cluster operators to create policies granting privileges to system components (ie. Knative) & users

#### 2. Allow list

An allow list would allow cluster operators to specify which ExternalName entries are to be included in Contour's routing tier.

I think this list would need to be host/port pairs - ie. Knative uses ExternalName to point to the envoy k8s service of a contour installation. We would only want routing to happen on port 80 or 443 and not any metrics/admin ports etc.

#### 3. EndpointSlices with CNAME Address Type

see: https://github.com/projectcontour/contour/issues/3950#issuecomment-904967484

#### 4. Other

There's probably other approaches but I can't think of anything - is there any discussion re: gateway APIs around this?

**Comment by stevesloka** [comment]
1. I think the first approach is interesting that allowing "system" accounts to have permissions to use the feature, but disallowing users to utilize them. It would move the enforcement to the cluster and out of Contour. 

2. Does this list need to be updated dynamically? We're looking to move the config to a CRD, but that's not there just yet. If it's dynamic, we'll need a way to know that list got updated. Alternatively, could use a regex to setup a range of valid entries for the allowlist. 

3. I'm not sure that GatewayAPI solves this in any way. There are ways to extend gatewayapi that are implementation specific. That's what I was mentioning the internal meeting earlier. Contour knows about all services in the cluster, but doesn't allow for cross-namespace references. However, doing something in this path ends up being specific to Contour and not transferable across other providers.

**Comment by tsaarni** [comment]
> 1. Remove the flag

I guess defaults can always be discussed (including usual "secure by default" vs "backwards compatible" arguments) but I think it would be important to keep secure option without requiring additional software to avoid use of insecure parts.

> 2. Allow list

From security point-of-view this could be good: it would avoid users from being in full control of routing destinations - assuming the user cannot also control which address the DNS resolves the destination hostname.

> 3. Other

Could Envoy RBAC filter be used to block the admin API?  Though we still are left with the more general CVE-2021-25740 vulnerability.

**Comment by youngnick** [comment]
I think it's important to remember that the reason that we've added this flag and set it to `false` by default is not only about the Contour CVE (although that was pretty bad), it's also about the fact that you can use ExternalName services to render anything anyone does with External Auth or Rate limiting meaningless, and this is outside of the control of the Contour owner.

Let me explain.

If I have a Service `secretsquirrel` in the namespace `secretsquirrel`, that I expose with a HTTPProxy that enables External Auth, Rate Limiting, and any other access-control features we add, having ExternalName Services enabled means that, if any user of the cluster knows that the `secretsquirrel` Service exists, they can expose it on an unauthenticated, un-rate-limited Ingress by creating an ExternalName Service that points to `secretsquirrel.secretsquirrel.svc.cluster.local`.

This totally breaks Contour's aim to be a secure-by-default solution, so when we realised that ExternalName Services could be used this way, we had no choice to add this flag and default processing of ExternalName services to off. Contour _must_ be as secure as we can make it by default, without needing to install any extra software. The flag also functions as an "I accept the risks" checkbox.

I know that this breaks Knative, and I'm sorry, but I can't knowingly ship an insecure Contour to the non-Knative users. I understand that Knative works in a different way and isn't really exposing the functionality to users, so the security context of using ExternalName is a bit different, but we gotta look after everyone.

In regards to the specific asks:
- I'm not prepared to remove the flag totally, or to change the default value. It's just too risky for unaware users. We can expose it via command line flag and env var as well as config file, if that will make things easier, but I'm unconvinced about removing it. I think allowing ExternalName services for any Ingress is a huge security hole.
- I'm one hundred percent supportive of having an allow list instead of just a boolean flag, since that's even safer than just allowing open slather on DNS names.
- We haven't discussed ExternalName services explicitly in Gateway API yet, but, since the kubernetes/kubernetes#103675 was found in the course of us designing cross-namespace things for Gateway API, I think we definitely will address it, although I don't really see any other option than saying "don't use ExternalNames".

**Comment by xaleeks** [comment]
I agree with Nick that as long as ExternalName has this kind of behavior, we should ship with the capability turned off by default to protect users unaware of this vulnerability.  It is actually recommended by CNCF if I remember correctly (I will try to dig up the exact phrasing).  That should be the default state, realized through whatever means and then we should deliver a way to adjust this through a flag or whitelist for the Knative team.    

The reason solution 1 might not be the best is because it seems to assume well established teams with separation of duties and knowledge of this issue with ExternalName.  

Since we are moving config to a new CR soon, maybe we can expose the allow list tuning in the CR.

**Comment by youngnick** [comment]
Just to clarify, @xaleeks, you mean "since we are moving to a new CR for configuration soon", right? HTTPProxy is staying around for a long time.

**Comment by xaleeks** [comment]
Yup, we are moving to using a CRD for representing the Contour config and the underlying Envoy so that this representation can be validated and reconciled by k8s.  HTTPProxy will be around for a long time indeed.

Have we shared this design with the community yet? If not, we should socialize the design from Steve Sloka

**Comment by youngnick** [comment]
I don't think we have shared that design yet, no.

**Comment by dprotaso** [comment]
Another alternative I discovered is that [`EndpointSlices` support `CNAME` address types](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#address-types).

They can RBAC'd separately from K8s Services and there's [guidance upstream about limiting write access](https://github.com/kubernetes/kubernetes/issues/103675). 

If Knative, instead of using `Service.ExternalName` or managing IP endpoints, we could create an `EndpointSlice` with a `CNAME` record. Thus we wouldn't need any of the suggested workarounds I outlined above. 

Related: https://github.com/projectcontour/contour/issues/2696

**Comment by youngnick** [comment]
That sounds like a good solution that will end up more secure for everyone @dprotaso. I guess the action for Contour there is to get that EndpointSlice support actioned?

**Comment by dprotaso** [comment]
> I guess the action for Contour there is to get that EndpointSlice support built?

Yup. Has there been any progress?

**Comment by dprotaso** [comment]
Knative is still on v1.18.x - is there anything new in v1.19 supporting this?

**Comment by youngnick** [comment]
There hasn't been any further progress on this yet, sorry.
