### ISSUE TITLE
Enable setting headers on all routes on ingress objects

### ISSUE THREAD

**Issue by artificial-aidan** [projectcontour/contour#4005]
**Please describe the problem you have**
[This](https://github.com/projectcontour/contour/issues/3258) issue describes a feature need to support linkerd. That works for HTTPProxy objects, but not for Ingress objects. With contours support for ingress objects, Contour needs a way to set headers on ingress objects too.

**Comment by youngnick** [comment]
Thanks for opening this issue, @artificial-aidan.

So, what you'd like is for the `headers` config stanza to be able to be applied to Ingress objects as well? I think that we could do that, but it would be a blanket apply, with no way to override on a per-Ingress basis. I'd probably want to do a boolean in the config file that's something like `applyToIngress`?

**Comment by artificial-aidan** [comment]
That sounds good to me. I think it would be reasonable not to have a per ingress override, that would be too many annotations. But a global override is required for some things.

A boolean would be great.

**Comment by youngnick** [comment]
Okay, if that's the case, here's the todo:
- Add a feature to the Contour configuration that allows the global header modification to be applied globally to all Ingress resources as well as HTTPProxy ones.
  - This should be either a boolean (`applyToIngress`), or possibly, a list of types to add the headers to. This isn't applicable to Gateway API because it has a Policy concept that's designed for this sort of use case.
- Out of scope: per-Ingress overrides like we have on HTTPProxy, since there's nowhere aside from annotations to put that on Ingress. It's all or nothing.

If you agree here, then I think this is implementable, probably even as a first issue.

**Comment by artificial-aidan** [comment]
I've started on this. I think I have it working for the most part. May have some questions about testing, and some other details tomorrow. I'll push up a branch when I clean things up a bit.

**Comment by youngnick** [comment]
Awesome, please feel free to push a draft PR if you want early feedback!

**Comment by stevesloka** [comment]
It might be a better spot to add these to the `virtualhost` of the HTTPProxy vs the global config. This way you could customize them per vhost and not have a per ingress controller default.

**Comment by artificial-aidan** [comment]
Are there `virtualhost` fields on ingress objects?

**Comment by stevesloka** [comment]
Sorry I misunderstood, I thought you wanted a global for httpproxy which came up before since this header needs applied to all routes. 

You'd need a config or annotation like @youngnick  suggested. I'd recommend against the boolean, just have a list of things you want to apply. If it's empty, then doesn't get applied. Also might just apply this to ingress resources. Httpproxy could go in the vhosts section of that which gives devs a way to configure themselves without access to contour config. 

We do probably need a way to let vhosts opt out.

**Comment by stevesloka** [comment]
Ok see about the boolean need, thinking if there's a smoother way to accomplish this. Let me think about it.

**Comment by artificial-aidan** [comment]
The httpproxy config was done in a different PR. I could see the benefit of a boolean as an improvement, but is it necessary at first? For the use case (linkerd proxy) there isn't a need to disable it.

**Comment by stevesloka** [comment]
Yeah maybe just mirror how httpproxy works, then can disable it of required in a future pr.

**Comment by artificial-aidan** [comment]
That's what the PR does. I'm away from work for a week, but can probably get to any review changes needed.

**Comment by youngnick** [comment]
I've just linked the PR that @artificial-aidan mentioned - #4018. I haven't had a proper look yet, sorry everyone.

**Comment by artificial-aidan** [comment]
I think this is closed with #4018
