### ISSUE TITLE
Add support for with_request_body

### ISSUE THREAD

**Issue by mfridman** [projectcontour/contour#4022]
After setting up envoy, contour and implementing an authorization server we noticed this setup does not work for SAML-based auth flows.

Specifically, the request body is not sent to the authorization server. We'd like to keep the AuthProvider in the same process as the ExtAuth service.

There was an issue filed and implemented to support per path filtering:
https://github.com/envoyproxy/envoy/issues/13285
https://github.com/envoyproxy/envoy/pull/13389

The documentation here:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=with_request_body#extensions-filters-http-ext-authz-v3-extauthz

There is a configuration example here:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter.html?highlight=with_request_body#configuration-examples

> One of the features of this filter is to send HTTP request body to the configured gRPC authorization server as part of the check request.

^ This is what we'd like to accomplish.

Is it possible to add support in contour to enable passing the request body to the authorization server? 

We rely on contour to manage the envoy configuration and would like to avoid setting filters in envoy directly through static files.

**Comment by youngnick** [comment]
This seems like a reasonable ask, thanks for the issue @mfridman.

Do you think that a boolean would be okay to start with, or would you need to tune the additional parameters (`max_request_bytes`, `allow_partial_message`, `pack_as_bytes`) as well? I'd prefer to start with a boolean and default these unless there's a strong need to do otherwise?

**Comment by mfridman** [comment]
Hi @youngnick, thank you for consideration. Yes, a boolean would work.

Assuming there is no limitation on the body size, we don't need those additional parameters. I mention this because SAML-based responses for ACS endpoints can be quite large, ~10KB.

**Comment by mfridman** [comment]
If this is something trivial for the maintainers to add that'd be awesome, otherwise I could take a look at submitting a PR. 

I presume this is a common task (syncing _some_ envoy options to be exposed via contour) .. maybe there is an existing PR you could point me at? If its a fairly trivial chunk of work I could submit a PR.

**Comment by abhide** [comment]
@youngnick I would like to work on adding support for this. Would that be fine? 
Seems like we can add options to 
`type AuthorizationServer struct` under `apis/projectcontour/v1/httpproxy.go`

**Comment by abhide** [comment]
If we add a boolean flag to what would be defaults for 
```code
      with_request_body:
        max_request_bytes: 
        allow_partial_message: 
        pack_as_bytes: 
```

Setting `max_request_bytes` could potentially increase memory usage for Envoy in high load scenarios; as the message body will be held in memory.

**Comment by mfridman** [comment]
> If we add a boolean flag to what would be defaults for
> 
> ```
>       with_request_body:
>         max_request_bytes: 
>         allow_partial_message: 
>         pack_as_bytes: 
> ```
> 
> Setting high value for `max_request_bytes` could potentially increase memory usage for Envoy in high load scenarios; as the message body will be held in memory.

I don't suggest setting arbitrary default values without giving users the option to modify them.

The simplest solution, for now, would be to add a boolean to allow users to opt-in to receive the _entire_ request body.

My worry is you add a boolean flag, but don't provide a way to modify the defaults, I'd be in the same position as I am today... no request body.

**Comment by abhide** [comment]
@mfridman thanks for your inputs. 
The part I am missing is: How would adding a boolean allow users to receive entire request body?
I read through proto documentation: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=with_request_body#extensions-filters-http-ext-authz-v3-buffersettings 
Didn't see the boolean flag you are referring to.

**Comment by mfridman** [comment]
You're right, there is no boolean flag. I meant the boolean flag would be a contour-specific implementation detail to either allow the request body through or not.

My concern is if these are hard-coded within contour with no ability to be modified then we still might have an issue if the request body is too large.

**Comment by abhide** [comment]
@mfridman thanks for your response.
Yes got it; boolean to enable/disable buffer settings and then expose those 3 options from Buffer settings.

@youngnick makes sense?

**Comment by youngnick** [comment]
I think that we should end up with something like this in the config file ( I can't remember off the top of my head if we already have a stanza for configuring external auth - if we do, these params should go in there.

The defaults should be the same as the Envoy defaults.

Otherwise:
```yaml
   extAuth:
    sendRequestBody: true
    withRequestBody:
      maxRequestBytes: 1024
      ...
```

I know that the Envoy properties use underscores, but we're trying to settle on goCamelCase instead to ease the transition to the Config CRD, so please stick with that naming style.

I'd like to see some +1s from other maintainers here too - @skriss @stevesloka @sunjayBhatia, any thoughts?

**Comment by abhide** [comment]
@youngnick I don't think there is a extAuth section in the configuration. Didn't find any here: https://projectcontour.io/docs/main/configuration/#configuration-file

ExtAuthz server is an instance of `ExternalService` CRD. 
```apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  name: htpasswd
  namespace: projectcontour-auth
spec:
  protocol: h2
  services:
  - name: htpasswd
    port: 9443
```

**Comment by sunjayBhatia** [comment]
seems like since we allow the ability to configure different auth servers per route potentially, we should also allow different behavior between them? so adding the options for request body passthrough/size on `HTTPProxy.Spec.VirtualHost.AuthorizationServer` sounds reasonable

**Comment by youngnick** [comment]
Hmm, they probably really belong _on tthe ExtensionService_, since they should be the same for all times that a particular ext_auth service is used. We can add them to ExtensionService for now, and this will be another thing for @skriss to take into account in the eventual ExtensionService redesign. I'd rather not add fields into HTTPProxy that may not stay there.

**Comment by sunjayBhatia** [comment]
In office hours we had discussed putting the fields on HTTPProxy, but if we want ExtensionService etc. to be refactored we might. have to wait for that to implement this request

**Comment by skriss** [comment]
> Hmm, they probably really belong _on tthe ExtensionService_, since they should be the same for all times that a particular ext_auth service is used.

@youngnick can you explain some more why you think Contour should impose this restriction? I ask because Envoy allows these settings to be varied for each use of an ExtAuth service, i.e. these are properties of the filter rather than the ExtAuth cluster, and also Contour currently allows at least one other ExtAuth filter property (`failure_mode_allow`) to be configured per use of an ExtAuth server, i.e. as `AuthorizationServer.FailOpen` on an HTTPProxy. So just trying to understand the difference between these two instances.

**Comment by youngnick** [comment]
Oh, okay, I had the wrong idea, I thought that this was the sort of thing that would be set for every instance of an ext_auth server, so it would make more sense to put things in therre. My mistake, putting them into HTTPProxy sounds correct in that case.

**Comment by skriss** [comment]
Added this to the 1.20 milestone as we have a PR from @abhide that's very close to ready.
