### ISSUE TITLE
add metric for DAG processing duration

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4059]
It'd be nice to have a metric capturing the duration of DAG rebuilds. We currently have metrics counting the number of DAG rebuilds and capturing the timestamp of the last DAG rebuild, but nothing that captures durations. This would be useful for understanding & debugging performance isuses.

**Comment by youngnick** [comment]
Hmm, I thought there was something in there already, I'll have a look.

**Comment by youngnick** [comment]
Nope, I was thinking of contour_dagrebuild_timestamp, which lets you know how often it's rebuilding, but not how long.

I think that we should probably add a summary metric, not a histogram one, since we don't have a great idea what the distribution will look like.  See https://prometheus.io/docs/practices/histograms/ for discussion of why to choose histogram or summary.

**Comment by skriss** [comment]
A nice-to-have here would be per-processor build times (could be done using labels, so `contour_dag_rebuild_seconds` with a label of `processor`, where each processor could be timed independently.
