### ISSUE TITLE
Load certificate from SDS server

### ISSUE THREAD

**Issue by freelich-du** [projectcontour/contour#4096]
Envoy supports loading certificate from user provided SDS server. https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret.html?highlight=sds
While Contour doesn't support it yet.
We need this feature to achieve better certificate management and reduce security risk.

**Comment by youngnick** [comment]
So, the connection to SPIRE is for the Envoy that Contour is running to get an mTLS _client_ certificate, that it will use to identify itself to your internal infrastructure, not to use SPIRE to issue TLS certificates for the external domain names reference by Ingress config?

**Comment by loveyana** [comment]
@youngnick It’s not. Maybe I didn’t explain too clearly. We need to use spire to issue TLS certificates for the external domain names referenced by the Ingress configuration. Because apigateway is outside the cluster, we let it call spire to obtain its mtls certificate and access back-end service cluster ingress, we want to use the Envoy that Contour is running to check the certificate and spiffeID it carries.

**Comment by youngnick** [comment]
Thanks @loveyana, I think it's important for us to be super clear on this one!

So, I think what you're saying is that the flow works like this:
- Spire is running somewhere, it issues TLS certificates for external domain names.
- You have an API Gateway outside the cluster that you want to connect to services inside the cluster (so you need a Ingress-style config to translate between outside-cluster things and inside-cluster things)
- You want the Ingress config to use the certificates generated by Spire.

Hopefully that's right.

If that is right, I still feel like the best thing to do would be to find a way to have Spire create Kubernetes Secrets automatically. It seems weird that it can't do this already, to be honest, given that it's designed to be used with Kubernetes. Then those Secrets could easily be used by Ingress or HTTPProxy objects, and Contour will handle passing them to Envoy when they are created or updated by the Spire integration.

If we did give the ability to configure another SDS server, the problem is that Contour needs to generate HTTPConnectionManagers for Envoy that reference the secrets in the Spire SDS _by name_, but Contour doesn't have a way to know the names Spire is using for the secrets in its SDS without also connecting to Spire itself. Without having a way for Contour to know the correct SDS secret name, I don't see how it would work.

So, I guess what I'm saying is, I understand what you're asking for, and it seems reasonable, but I don't feel confident that if we built it, it would actually give you the functionality you want. I _strongly_ recommend trying to see if you can get Spire to write out the generated TLS certificates as Kubernetes Secrets instead.

**Comment by evan2645** [comment]
> If we did give the ability to configure another SDS server, the problem is that Contour needs to generate HTTPConnectionManagers for Envoy that reference the secrets in the Spire SDS by name, but Contour doesn't have a way to know the names Spire is using for the secrets in its SDS without also connecting to Spire itself. Without having a way for Contour to know the correct SDS secret name, I don't see how it would work.

Sorry for digging up the stale issue, but it continues to pop up. Thought I'd drop a quick note here that SPIRE can be [configured to use a static SDS secret name](https://github.com/spiffe/spire/blob/main/doc/spire_agent.md#sds-configuration) (in fact, I believe it does this by default), which could then also be configured on Contour.

**Comment by tsaarni** [comment]
Is https://spiffe.io/docs/latest/microservices/envoy/ targeting the service mesh use case, where each service is co-located with their own "sidecar" instance of Envoy? Each service gets only single workload identity and therefore the local Envoy fetches just single SDS secret, served by the local SPIRE agent by the default SDS name `default_svid_name`. Is that how it is used? 

How would that map to a use case where Envoy acts as an ingress proxy, and it should be able to act as server on behalf of several virtual hostst / domains (according to the `HTTPProxy` definitions), each with their own identities/server certificates? Like @loveyana wrote:

>We need to use spire to issue TLS certificates for the external domain names referenced by the Ingress configuration.

In the service mesh use case, a single certificate may be used by the sidecar Envoy as both server certificate when accepting inbound TLS connections from the mesh, as well as client certificate when initiating outbound connections to the peers in the mesh. In ingress use case Envoy is expected to serve several certificates in inbound direction from external clients. However, when it then routes the requests to upstream, towards backend services within the cluster, currently we only allow single client certificate for the upstream connections. Would that upstream use case map better with the certificate that SPIRE agent serves by default SDS name?
