### ISSUE TITLE
[Question]HTTP -> HTTPS redirect when TLS is terminated at AWS ELB

### ISSUE THREAD

**Issue by georgestoica-prive** [projectcontour/contour#4211]
We are evaluating Contour as a replacement for our existing Ingress Controller implementation on EKS.
Currently TLS is terminated at ELB.
We want to be able to redirect incoming `http` traffic to `https`. After going through the documentation i could not find a reference to this use case.
Can this be done using `HTTPProxy` or by Contour configuration?

**Comment by youngnick** [comment]
This is not documented because it's on by default. 😄 

If you use HTTPProxy or Ingress to configure a HTTPS route, Contour will automatically create a 301 redirect for Envoy.

However, when you are terminating TLS upstream rather than on Envoy, the situation is more complicated, because all the traffic that Envoy will see is HTTP.

It seems that you need a way to check the scheme in the URL, and issue a 301 if it's HTTP?
