### ISSUE TITLE
Open the TCP port without TLS?

### ISSUE THREAD

**Issue by lou-lan** [projectcontour/contour#4222]
**What do you want the project to decide?**

The context is some IP TCP-based services that are publicly available without the use of TLS.

**Anything else you would like to add:**

**Comment by youngnick** [comment]
Right now, Contour only supports exposing TCP services that are exposed wrapped with TLS - this enables Contour to only use a single TLS TCP port for exposing many services.

Changing this will require changing a few things (for one, Contour and Envoy currently open only two ports). We already have a couple of issues open for these, see #3086 and #2922 for some issues, and #3263 for a previous stab at this. Because Envoy runs in cluster, it's actually quite a bit more complicated to make everything *just work* than you might think.

I'll close this out, and encourage you to add some info on #3086 to help us prioritize it.
