### ISSUE TITLE
Contour unable to handle 3-byte wide UTF-8 character in query parameter

### ISSUE THREAD

**Issue by jinnypark9393** [projectcontour/contour#4253]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
We're currently using Contour on Tanzu Kubernetes Grid environment.
After implementing Contour, we have 400 error when we includes 3-byte wide UTF-8 character in query params using IE11 with http protocol.
For example: ```http://www.example.com/user?name=이름```
(It works fine on Chrome browser and IE11 with https protocol.)

I know this is envoy originated issue(https://github.com/envoyproxy/envoy/issues/12073)
but I'm wondering if Contour have a resolution or bypass of this issue.

**What did you expect to happen:**
Returns HTTP 200 code & Accessed the application but it returns HTTP 400 error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Contour version: v1.12.0
- Kubernetes version: (use `kubectl version`): v1.20.5–vmware.2
- Cloud provider or hardware configuration: Azure with Tanzu Kubernetes Grid
- Envoy version: v1.17.3

**Comment by sunjayBhatia** [comment]
I think currently the only workaround would be to recompile Envoy in non-strict HTTP parsing mode, since for HTTP1.1 that component comes before any other settings Contour would modify in request processing

you could modify this list of options: https://github.com/envoyproxy/envoy/blob/2e6db8378477a4a63740746c5bfeb264cd76bc34/bazel/external/http-parser.BUILD#L15 to add `-DHTTP_PARSER_STRICT=0` and recompile Envoy following their docs (heres a good start: https://github.com/envoyproxy/envoy/blob/main/bazel/README.md)

**Comment by skriss** [comment]
We're not currently planning on making any changes here, closing this out.
