### ISSUE TITLE
Understanding Idle Connection Timeout

### ISSUE THREAD

**Issue by dev-chirag** [projectcontour/contour#4338]
Hi,

I was a bit confused about the configuration param - **connection-idle-timeout**

The documentation says that "The timeout applies to downstream connections only", so that means the idle connection timeout is supported with external clients or backend servers? 

So actually wanted to understand whats downstream and upstream from Contour point of view. This confuses me more #4330 

Thanks

**Comment by youngnick** [comment]
Yes, this means the timeout applies to external clients only. Importantly, the behavior changes slightly depending on if you're using HTTP/1.1 or HTTP/2 - for the former it's an inter-request timeout, for the latter it's a inter-stream timeout. It's not really as meaningful for HTTP/1.1 connections though, since they generally don't hold connections open.

**Comment by dev-chirag** [comment]
Thank you so much @youngnick , that was fast. 

Closing this issue.
