### ISSUE TITLE
Gateway API: support merging listeners across Gateways

### ISSUE THREAD

**Issue by mmalecki** [projectcontour/contour#4358]
We currently only support a single `Gateway` per a `GatewayClass`. Once a second gateway gets created, it doesn't get `Scheduled` with `OlderGatewayExists` reason.
I'm aware of nothing in the specification that would prohibit us from handling multiple `Gateway`s.

In particular, for my use-case, I'm after a solution that would support assigning the same IP address to two gateways (via the same mechanism that currently fetches Envoy's IP), both handling different hostnames. This way, in my `HTTPRoute`s I can point at a gateway, instead of matching the hostname via rules. (Although I believe this particular use-case may be at odds with #3545.)

**Comment by sunjayBhatia** [comment]
yeah currently we only support a single Gateway, though the spec does say:
```
An implementation MAY group Listeners by Port and then collapse each group of Listeners into a single Listener
if the implementation determines that the Listeners in the group are “compatible”.
An implementation MAY also group together and collapse compatible Listeners belonging to different Gateways.
```

Also to restate/understand, in your case it seems you want to have say Gateway 1 with HTTP listener for foo.com and Gateway 2 with HTTP listener for bar.com, rather than a single Gateway with an HTTP listener that has routes attached which themselves do the foo.com vs bar.com matching (via Hostname field on HTTPRoute)

**Comment by mmalecki** [comment]
Hey @sunjayBhatia,

> Also to restate/understand, in your case it seems you want to have say Gateway 1 with HTTP listener for foo.com and Gateway 2 with HTTP listener for bar.com, rather than a single Gateway with an HTTP listener that has routes attached which themselves do the foo.com vs bar.com matching (via Hostname field on HTTPRoute)

That's correct. Happy to hear about the spec-given right to collapse multiple listeners into a single one by port. That would satisfy my use-case 100%.

As I understand, there doesn't seem to be a spec or any planning on Contour side to implement this. Would it be a terrible bother if I started poking around the source code and asked a question here and there, in order to get that implemented?

**Comment by sunjayBhatia** [comment]
cc @skriss since this is related to work youre doing around Gateway API

**Comment by skriss** [comment]
Hey @mmalecki thanks for starting this discussion. Could you provide some more context on why you prefer to have the hostname matching on the `Gateways`, rather than on the `HTTPRoutes`? Also, is having the same IP address for both a hard requirement? Or would having one Contour+Envoy instance per Gateway also be workable for you?

**Comment by mmalecki** [comment]
Sorry for the late reply here.

> Could you provide some more context on why you prefer to have the hostname matching on the Gateways, rather than on the HTTPRoutes?

Sure thing - in short, I'd prefer to have hostname matching done on the `Gateway`s vs `HTTPRoute`s so that my manifests don't have to contain actual domains (varying between environments), with the integration point being the gateway name instead (well-known string).
This way the DNS name becomes an implementation detail, with cluster operators managing ingress from top to bottom.

> Also, is having the same IP address for both a hard requirement? Or would having one Contour+Envoy instance per Gateway also be workable for you?

I'm just a random guy making an issue, nothing here is really a hard requirement ;). That said: I think everyone paying their cloud bill would prefer being able to roll these up into one one instance (as it would require multiple load balancers otherwise).
Additionally, I haven't explored this option, but I think achieving this with a separate Contour and Envoy per `GatewayClass` + `Gateway` (using different `controllerName`s) is already possible with no code changes.

**Comment by xaleeks** [comment]
What's being proposed doesn't seem to mesh well with the original intent stated in https://gateway-api.sigs.k8s.io/v1alpha2/api-types/gateway/.  The Gateway seems to represent the config of the infrastructure, so you can treat it as a network point.  Having hostname resolving to Gateway seems too powerful, and there's already an elegant way of doing this through HTTPProxy today.

**Comment by youngnick** [comment]
It's absolutely intended that Gateway Listeners be able to discriminate traffic based on a hostname, that's why the field is in there. We kind of intended that separate Gateways with Listeners that don't conflict could be mergeable onto a single load balancer (in the Gateway API, I mean), but we haven't got to the stage where we can actually do that with Contour yet.

As far as the upstream API is concerned @mmalecki, I'd recommend you look at using a single Gateway for now with Listener names, and use the `sectionName` field in the HTTPRoute ParentRef to choose only that Listener to attach to. Although, now that I mention it, I'm not sure if we've implemented that in Contour yet. @skriss?

**Comment by skriss** [comment]
> It's absolutely intended that Gateway Listeners be able to discriminate traffic based on a hostname, that's why the field is in there. We kind of intended that separate Gateways with Listeners that don't conflict could be mergeable onto a single load balancer (in the Gateway API, I mean), but we haven't got to the stage where we can actually do that with Contour yet.
> 
> As far as the upstream API is concerned @mmalecki, I'd recommend you look at using a single Gateway for now with Listener names, and use the `sectionName` field in the HTTPRoute ParentRef to choose only that Listener to attach to. Although, now that I mention it, I'm not sure if we've implemented that in Contour yet. @skriss?

Yep, that's a great point @youngnick, that is probably the best way to go. You can set up multiple Listeners on a single gateway, each with the same port but a different hostname, and then when `HTTPRoutes` select them, provide the specific Listener name in the `sectionName` field (see https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.ParentReference for details). I have been testing scenarios like that recently and all seems to work well.

**Comment by skriss** [comment]
Just recording another idea I've had around this - you could actually define a GatewayClass parameter to indicate whether or not to merge Gateways of a given GatewayClass into a single set of infra. That way, folks who want to consolidate infra can specify that via their GatewayClass and get things merged, whereas folks who want dedicated infra per Gateway can do that as well. Might be a nice way to handle both use cases.
