### ISSUE TITLE
severity instead of level in logging

### ISSUE THREAD

**Issue by movikbence** [projectcontour/contour#4414]
Hi

I am checking contour logs, and we have a query about if the "level" field can be changed to "severity" in contour logs.
Here is the example:

"time="2022-03-16T11:58:42+01:00" **level**=error msg="stream terminated" connection=114 context=xds error="rpc error: code = Canceled desc = context canceled""

Our customer has a way to transform the logs into json, then visualize with Elastic Search and something is messing up the severity.
I believe if the level field would be severity, the status would be correct.

Is there a way to make a workaround for it?

Thank you in advance.

- Contour version: 1.15.2
- Kubernetes version: (use `kubectl version`): 1.21
- Kubernetes installer & version: 1.21
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from `/etc/os-release`): sles

**Comment by youngnick** [comment]
The logging library Contour uses, [logrus](https://github.com/sirupsen/logrus), puts this field in for us automatically, and it doesn't seem to be customisable. It does support outputting directly to JSON, but we don't have a way to let you tell Contour to do that.

So, it doesn't seem like we can easily change the `level=` part of the line, but we could maybe make it so that it's JSON directly, without needing a translator? Would that help?

**Comment by movikbence** [comment]
sorry for the late reply, we were also investigating internally our possibilities. Such logging would be really valuable for us

**Comment by youngnick** [comment]
Okay, so we will need a config setting or command line switch to set _Contour's_ logs to JSON output. @projectcontour/maintainers, any thoughts? Note that we already have a way to set _Envoy's_ logs to JSON output, just not Contour's.

**Comment by movikbence** [comment]
envoy's log to JSON is regarding the access log, not the whole logging mechanism as I know
https://projectcontour.io/guides/structured-logs/
