### ISSUE TITLE
Add grpc_status_number to access logs

### ISSUE THREAD

**Issue by rajatvig** [projectcontour/contour#4484]
Envoy 1.22 supports reporting the grpc_status_code in access logs and as referred to in the [pull request](https://github.com/projectcontour/contour/pull/4424), it should be included in the default log pattern when using JSON.

**Comment by sunjayBhatia** [comment]
the tricky thing here is even though it is a totally new feature, i think the crossed out bits in comment https://github.com/projectcontour/contour/pull/4424#issuecomment-1101785837 still does stand, since you could update contour and change the access log format at the same time as upgrading envoy, so you could send invalid access log formats to older Envoys

this may degrade fine, since at least the percent encoded format specifiers Envoy doesn't know about will be just kept without translating them, so maybe not the most risky

**Comment by youngnick** [comment]
I think that waiting until after 1.21 for this one is probably better, but not strongly so.

**Comment by sunjayBhatia** [comment]
moving to 1.22

**Comment by rajatvig** [comment]
Have an open pull request to address the issue
