### ISSUE TITLE
Gateway API : authorization with HTTPRouteFilter

### ISSUE THREAD

**Issue by stockymcstockface** [projectcontour/contour#4530]
Hi,
Is it possible to do authorization using ExtensionService with current implementation of Gateway API v1alpha2 ?
I have been reading this walkthrough https://projectcontour.io/guides/external-authorization/ and managed to have basic http authorization but I fail to achieve this using gateway.networking.k8s.io/v1alpha2 HTTPRoute resource and a filter with extensionRef, just like in the doc.
Will it be implemented in the future ?

Thanks.

**Comment by sunjayBhatia** [comment]
xref: https://github.com/projectcontour/contour/issues/4675

**Comment by sunjayBhatia** [comment]
Apologies @stockymcstockface for not getting back to you sooner

> Will it be implemented in the future ?

Hopefully yes, we're starting discussion on #4675 about how to implement the `extensionRef` mechanism to enable these sorts of features

I'm inclined to close this one out in favor of https://github.com/projectcontour/contour/issues/4675 since there is a little more content there
