### ISSUE TITLE
Does Gateway API supports HTTP2 / gRPC routing

### ISSUE THREAD

**Issue by joda01** [projectcontour/contour#4665]
I'm using the gateway API of contour and want to route gRPC requests.
Does the HTTPRoute resource
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
``` 
supports routing of http2/grpc messages?

Further question:
Is it planned to support the resource
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
``` 
as described in https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRoute

**Environment:**

- Contour version: 1.22.0
- Kubernetes version: v1.23.2
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure AKS

**Comment by sunjayBhatia** [comment]
I'm not quite sure on our plans around GRPCRoute since it is an "extended" support feature, however to enable HTTP/2 communication between Envoy and your backend gRPC service, you can set the annotation `projectcontour.io/upstream-protocol.h2` (or end with `h2c` if you are using plaintext) on the service associated with your app to the appropriate service port (see https://projectcontour.io/docs/v1.22.0/config/annotations/#contour-specific-service-annotations)

**Comment by sunjayBhatia** [comment]
I'm working on a general guide to configuring contour ingress to gRPC apps, will include some detail on how it works right now for Gateway API

**Comment by joda01** [comment]
@sunjayBhatia Thank you very much for your fast response! I'll give it a try.

Best Greetings
