### ISSUE TITLE
Need contour to support regex for CORS- alloworigin field

### ISSUE THREAD

**Issue by sri-rajar** [projectcontour/contour#4666]
Contour alloworigin field for CORS policy is not supporting pattern matching on domains (like *.vmware.com) .

Envoy has ability to provide regex  support https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/string.proto#envoy-v3-api-msg-type-matcher-v3-stringmatcher  with safe_regex  option

The ask is for contour to support regex pattern matching for the allowOrigin field in CORS policy.

**Comment by skriss** [comment]
Tentatively adding to 1.23 milestone.

**Comment by sunjayBhatia** [comment]
This looks doable, other than piping config through the only other significant piece of work is to ensure we properly validate regex patterns passed in by users and differentiate them from specific origins

since the `allowOrigin` field is a string slice, not a structured type, we have to be mindful of that, and *maybe* have to deprecate this field and introduce a more structured type for this field if necessary, but hopefully we can do it in-line

**Comment by sunjayBhatia** [comment]
@sri-rajar check out this draft pr: https://github.com/projectcontour/contour/pull/4710 for an early preview!
