### ISSUE TITLE
Question about provisioner generate resources

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#4731]
the `gatewayReconciler` only watches resources: `GatewayClass` & `Gateway`, the other resources such as `Deployment` and `Service`  is not watched, if they are deleted by manual, they will not be recreated again, it leads to the contour will not work, so do not watch them is a design decision, or a not finished work?

**Comment by skriss** [comment]
@izturn I think it's a little bit of both. The initial motivation for the Gateway provisioner was to be able to run & pass the Gateway API conformance tests, so we prioritized implementing the functionality needed for that, primarily around provisioning. However, the precise details of how Gateway infrastructure should be continuously reconciled is still an area to sort out (xref #4473). One complication is related to how the Gateway API spec describes how GatewayClass parameters should be treated:

> ...a Gateway is based on the state of the GatewayClass at the time it was created and changes to the GatewayClass or associated parameters are not propagated down to existing Gateways. This recommendation is intended to limit the blast radius of changes to GatewayClass or associated parameters.

So, we don't always want to be reconciling Gateway infra to the current state of the GatewayClass, we should really only be reconciling the parts of the Gateway that are expected to change (e.g. listeners, addresses).

Circling back to your original scenario, we'd need to figure out what to do (if anything) in the scenario you describe - should we re-instantiate the Service, using the current GatewayClass params? Should we capture the GatewayClass params used at the time of provisioning the Gateway somewhere, so that we maintain a point-in-time snapshot of them to be used in this scenario? Should we not concern the provisioner with restoring accidentally deleted infra and avoid/solve that issue in a different way?

This is a long-winded way of saying, I think that there is further development to be done here, but it's not quite as simple as just throwing a continuous two-way reconciliation on top of all the resources. If this is something you're interested in, we probably need to do some design work before moving ahead with an implementation.

**Comment by skriss** [comment]
Closing out this question, feel free to reopen or open other issues if needed.
