### ISSUE TITLE
upgrade tests getting wrong "from" version on release branch before release tag created

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#4809]
https://github.com/projectcontour/contour/actions/runs/3290540851/jobs/5423694404#step:7:142

This is on a release branch, but before a tag has been created on that branch. It should be upgrading from the latest tag in this case (i.e. v1.22.1).

https://github.com/projectcontour/contour/blob/main/test/scripts/get-contour-upgrade-from-version.sh#L10-L12 is the code in question. Needs to handle both (a) release branch that doesn't yet have a tag created on it; and (b) older release branches, i.e. `release-1.22`, where the "from" should be the latest v1.22.x tag.

**Comment by sunjayBhatia** [comment]
I think the main issue here is that there are some really old tags that are on `main` rather than a release branch and therefore on any newly created release branches, so https://github.com/projectcontour/contour/blob/cd9a770bc1aeab39d7e741c048dd77bed49b41e9/test/scripts/get-contour-upgrade-from-version.sh#L12 will find that (v1.2.0)

**Comment by sunjayBhatia** [comment]
actually It seems its only v1.2.0 which was improperly tagged on `main`
