### ISSUE TITLE
TLS handshake is failing immediately after client hello packet

### ISSUE THREAD

**Issue by manojnc** [projectcontour/contour#4817]
**What question do you have?:**
After upgrading the contour version to 1.22.1, TLS handshake is failing. Server sends a connection reset immediately after client hello packet is sent. I have verified that the envoy is listening on port 8443. Minimum protocol version has been set to 1.2. I enabled the debug logs but nothing related to TLS error is getting logged there. I have run out of new ideas to debug this further and I am new to using contour + envoy. I would appreciate any help to narrow down this further. 

**Anything else you would like to add:**

curl --resolve my.host:8443:kube.worker.ip https://cmy.host:8443/health-check -Ivvv
* Added my.host:8443:worker_internal_ip to DNS cache
* Hostname my.host was found in DNS cache
*   Trying kube_worker:8443...
* Connected to my.host (xxx.xxx.xxx.xxx) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to my.host:8443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in my.host:8443 

envoy is indeed listening on port 8443.
sudo netstat -anpe | grep 8443
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      65534      9034266    32321/envoy

**Environment:**

- Contour version: 1.22.1
- Kubernetes version: (use `kubectl version`): 1.23
- Kubernetes installer & version:1.22
- Cloud provider or hardware configuration: amazon-eks-node-1.22-v20220926
- OS (e.g. from `/etc/os-release`):

**Comment by tsaarni** [comment]
Here are couple of things that can be checked:

Since you mention the problem appeared after upgrade, I assume you mean that exactly same configuration worked before upgrade?  Did you check the status of `HTTPProxy` resource (if that is what you use) to see it shows valid state? Is the configured virtualhost in `HTTPProxy` matching the requested hostname? In your example, you use host `cmy.host` in URL but `--resolve my.host`, was it just a typo here in the issue?  Have you tested with `openssl s_client -connect kube.worker.ip:8443 -servername my.host`, does that give any further clues on what could be wrong? Does the problem persist after Contour and Envoy restarts?

**Comment by manojnc** [comment]
Thank you for your sharing these inputs @tsaarni 
It was http proxy which was causing the issue. It was expecting the tls certificate to be present in the projectcontour namespace as well along with a copy in default. This is a change from previous versions I was using as we introduced fallback certificate for aws alb. But, thanks for your help here. Your comments made me focus on the  httpproxy.
