### ISSUE TITLE
Question about "installing multiple Contour instances"

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#4899]
**What question do you have?:**
     With https://github.com/projectcontour/contour/pull/4832, we can installing multiple Contour instances per cluster, but the `informOnResource` for resources such as `ExtensionService` had not namespaced. It leads to one contour watch the events for the others.
     Should we namespaced for them, like for `Secret`?
     If you all like this idea, I will send a pr.

**Comment by sunjayBhatia** [comment]
If we do this we will have to have some sort of flag letting Contour know it is intended to only run in a single namespace. We will also need to make a decision on and document what it means for inclusion/delegation, TLSCertificateDelegation, GW API ReferenceGrants, etc. when running in this mode, since those are intended cross-namespace reference mechanisms.

**Comment by skriss** [comment]
Note, this is being addressed in #5214
