### ISSUE TITLE
Change respond timeout for each ingressclass 

### ISSUE THREAD

**Issue by Sinamcp** [projectcontour/contour#5544]
**What question do you have?:**
I want to know is there any option to change default  response timeout for all of httpproxy at envoy level not httpproxy object, I know default is 15, But i want to change the default value for each ingressclass

for example we have 3 ingressclasses:

private ---> 30s
inter-dc ---> 15
Public ---> 5s

**Environment:**

- Contour version: 1.25
- Kubernetes version: (use `kubectl version`): 1.23
- Kubernetes installer & version: openshift (OKD 4.10)

**Comment by skriss** [comment]
@Sinamcp there is not currently a way to do this, no. Contour doesn't really support attaching any policy to an ingress class, apart from if you are using different instances of Contour per ingress class and have different global configuration for each (which wouldn't work for response timeouts anyway since those need to be set per-HTTPProxy).
