### ISSUE TITLE
envoycert and contourcert doesnt auto renew

### ISSUE THREAD

**Issue by mpsanj** [projectcontour/contour#5556]
Hi Team,

 We are using contour v1.20.1, pretty much has satisfied all our use cases so far, but we ran into an issue yesterday, where the envoy containers failed to startup and found the below logs:
 
 reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
 
 
 Found this doc https://kb.vmware.com/s/article/90811, which stated to delete the expired envoycert and contourcert, which was on checking were expired. Isnt there some auto renewal process in place ? Or how can we keep track of it ?
 Any best practices around it, please advice.
 

k8s version: v1.24

**Comment by skriss** [comment]
@mpsanj by default, the certs generated by the contour certgen job are valid for a year (https://github.com/projectcontour/contour/blob/main/pkg/certs/certgen.go#L42). They get re-generated every time you upgrade Contour since a new certgen job is created, so the assumption is that either you upgrade at least once a year, or you're manually re-generating the certs (see e.g. https://projectcontour.io/docs/1.25/grpc-tls-howto/#rotate-using-the-contour-certgen-job).

**Comment by skriss** [comment]
xref #2149
