### ISSUE TITLE
Question about multiple listeners under NodePort mode

### ISSUE THREAD

**Issue by izturn** [projectcontour/contour#5733]
Hey @skriss:

Our customer has configured several contours  (`C1`, `C2`, `......`) in NodePort mode behind a nginx server (N). The nginx server redirects traffic to C1:80, C2:80 (`http/80`), and so on. Everything was working fine until they upgraded contour to v1.26.0.

![code](https://github.com/projectcontour/contour/assets/44051386/f3fd0dc3-5e95-4013-a47c-7ac0a757e411)

According to our observations the code `port.NodePort ==port. ServicePort` as above leads to that, we are looking for a solution that doesn't require changing all the nginx configurations to make the contours work again. 

My have the following questions:
  1. Why `port.NodePort == port.ServicePort`?
  2. Can we add the option(s) to allow users to customize the `NodePort` and more?

**Comment by izturn** [comment]
@skriss  ping

**Comment by izturn** [comment]
ping @skriss

**Comment by skriss** [comment]
It seems like you're actually being affected by the change to the _service port_, not the node port, since the node port should still be getting set to the value of the gateway listener port when a NodePortService is provisioned.

Previously, when provisioning a NodePortService, the service ports were statically set to 80/443 for the two allowed listeners, but now that many listeners and many ports are allowed, those have to be set to non-static values to avoid conflicts, hence why they're also getting set to the gateway listener port values.

Ultimately, it seems like you have a need to specify both a node port and a service port value, which Gateway API does not currently enable. There is an upstream issue on this (https://github.com/kubernetes-sigs/gateway-api/issues/2321) which I would suggest commenting on to help amplify.

**Comment by izturn** [comment]
ok, thx for your explain
