### ISSUE TITLE
Gateway API: set supported version condition on GatewayClass

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5754]
ref. https://github.com/kubernetes-sigs/gateway-api/pull/2384

**Comment by sunjayBhatia** [comment]
Todos here:
- add RBAC for and fetch `gatewayclasses.gateway.networking.k8s.io` CustomResourceDefinition
  - on provisioner startup? or maybe better on each GatewayClass reconcile loop so if the CRDs are changed, we can find that out?
- if resource has `gateway.networking.k8s.io/bundle-version` annotation value that is not supported, then add status condition `SupportedVersion: False` with appropriate reason/message (otherwise True)
- make a decision on what versions are supported
  - do we support version skew?
  - if so, need to test multiple versions of the CRDs
  - what happens if CRD bundle version is updated to an unsupported version?
