### ISSUE TITLE
Gateway API: fix for GatewayStaticAddresses conformance test

### ISSUE THREAD

**Issue by skriss** [projectcontour/contour#5922]
In Gateway API 1.0, a GatewayStaticAddresses conformance test has been added. Contour is not currently passing this test, however Contour does have basic support for Gateways to specify addresses and have them be reflected in the Envoy service. This issue is to investigate the failure and get the test passing (or add detail as to why it can't).

**Comment by skriss** [comment]
Looks like there are a few things we need to do to get this test passing:

1. in the test suite setup, set UsableNetworkAddresses and UnusableNetworkAddresses
    a. `UsableNetworkAddresses` must contain an address that can be used/assigned for the Gateway
    b. `UnusableNetworkAddresses` must contain an address that is **valid** but can't be assigned to the Gateway (see AddressNotUsable in https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayConditionReason)
1. In the provisioner, if a Gateway has an unsupported address type in spec, set a condition of `Accepted: false (UnsupportedAddress)`.
1. Somewhere we need logic to detect and set the `Programmed: false (AddressNotUsable)` condition for 1b. I'm not sure off the top of my head how this should work.

**Comment by sunjayBhatia** [comment]
To be able to detect `AddressNotUsable` my first thought is that we'll have to add something like an "allowed Gateway address range" so we can detect an invalid address value and flag it in status

we do run into a bit of a fun issue, in that as of now we've let the Provisioner handle the Accepted condition and contour controller handle the Programmed condition for Gateways, in the `AddressNotUsable` case we will need to have the Provisioner take over that condition as well

**Comment by sunjayBhatia** [comment]
Running into a few issues that make me think this might need to write up a full design:

#### Gateway Accepted Status updates
- The Gateway Provisioner previously only ever set the status Accepted: True and left the rest of the status updates to the main controller
- The controller assumes if it is running then the Gateway was Accepted, which was previously true
- With static address support, we can have an invalid Gateway configuration that the Provisioner needs to figure out and set Accepted: False
  - The Provisioner should likely be the component that knows if a requested address type is valid
- This is simple on a Gateway create, we don't continue with setting up contour if the Gateway is not Accepted
- However if a Gateway is updated after it was valid before and becomes invalid what do we do?
  - Having the Controller and Provisioner synchronize on Status conditions is racy and error prone
  - Even if we do the above, what happens to a running Contour's configuration from the previously valid Gateway? we don't have a good way to roll back and not drop working traffic
  - Having the Provisioner tear down a Contour whose Gateway is now invalid seems wrong
- This does not seem like a field we can say we will not re-reconcile, legitimate updates to addresses should be respected

#### Gateway Programmed Status updates
- Currently the controller can set Programmed: False if not all Listeners are valid, requested addresses not in status
- The Provisioner should likely be the component that knows if a requested address is usable
- Needs to set Programmed: False status if address is unusable
- Again we have some possible fighting/raciness over Status conditions

#### Gateway Status Address
- Currently populated by the Controller monitoring the Envoy LoadBalancer Service that is created by the Provisioner
- When that gets an address, it is set in the Gateway status
- We explicitly ignore Status updates for Gateways in the event handler, so a Gateway can be initially set to Programmed: False because no addresses were set, but we never see the updated Gateway so it can stay that way forever, another race condition
- (Ignoring status updates likely is related to the topics above too)
- *Would it make sense to move the Gateway status address updater into the provisioner instead?*

**Comment by sunjayBhatia** [comment]
WIP branch: https://github.com/sunjayBhatia/contour/tree/fix-gw-api-conformance-static-address

**Comment by sunjayBhatia** [comment]
TODO from issue triage: look into upstream discussions on addresses to see how this interacts with the Service address field being deprecated
```
	// Only applies to Service Type: LoadBalancer.
	// This feature depends on whether the underlying cloud-provider supports specifying
	// the loadBalancerIP when a load balancer is created.
	// This field will be ignored if the cloud-provider does not support the feature.
	// Deprecated: This field was under-specified and its meaning varies across implementations.
	// Using it is non-portable and it may not support dual-stack.
	// Users are encouraged to use implementation-specific annotations when available.
	// +optional
	LoadBalancerIP string `json:"loadBalancerIP,omitempty" protobuf:"bytes,8,opt,name=loadBalancerIP"`
```
