### ISSUE TITLE
Envoy's Cache update pattern can be problematic 

### ISSUE THREAD

**Issue by shadialtarsha** [projectcontour/contour#5983]
**What steps did you take and what happened:**
- Production stack that was handling thousands for RPS
- I added the global External Auth config to Contour and wasn't expecting any calls to go to my external auth service as the config was disabled by default.
- Envoy briefly called the external auth during the rollout and caused issues.

**What did you expect to happen:**
No calls should have gone to the external auth service

**Anything else you would like to add:**
The problem is, currently Contour doesn't update the cache with the whole dag, instead, Contour updates the listener's resources first which causes the external Auth filter to be applied before updating Envoy with the routes resources that have the Auth disabled on them. During this period between the two updates, the problem occurred.

A potential solution could be, updating Envoy with the whole dag on a cold start.

**Comment by sunjayBhatia** [comment]
We recently improved the startup cache warming with https://github.com/projectcontour/contour/pull/5672, which ensures the initial startup of the xDS server and DAG build does not occur until all relevant resources in the cluster have been cached

The issue you describe however does not sound like a startup problem but rather a fundamental SOTW xDS problem when not using the ADS flavor of SOTW xDS. ADS should guarantee a more correct ordering of resources sent to Envoy so that for example Listeners are instantiated after Routes are populated. With plain SOTW xDS, there is no ordering between the different discovery request streams for different resource types.

We'll need to revive the work to enable ADS and you will need to switch to the go-control-plane based xDS server to take advantage of this.
