### ISSUE TITLE
Expose payload_in_metadata and claim_to_headers to facilitate information retrieval from JWT token

### ISSUE THREAD

**Issue by bwu-contour** [projectcontour/contour#5992]
One capability Envoy has is around authenticating that a given request is valid, based on the configurations specified by Contour.

In Contour this is achieved by defining a [JWTProvider](https://projectcontour.io/docs/1.25/config/api/#projectcontour.io/v1.JWTProvider). In Envoy it's implemented by the [jwt_authn](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#extensions-filters-http-jwt-authn-v3-jwtprovider) filter. However, Contour is only able to configure a subset of Envoy functionality related to jwt_authn filters. One capability Envoy has that Contour does not expose is the ability to extract information from a requests authentication token and store it for future use during request handling (payload_in_metadata or claim_to_headers).

We propose enhancing Contours existing JWTProvider configuration object with these two additional fields to surface the ability to configure Envoy’s payload_in_metadata and claim_to_headers functionality.

**Comment by sunjayBhatia** [comment]
Thanks for making this issue @bwu-contour 👍🏽 

I believe when we discussed this offline, you were interested in extracting JWT payloads to Envoy filter metadata in order to put some content of the JWT payload into access logs. It would be good to capture that and any other end-to-end Contour user/application developer/operator facing features in the issue description so we have a more fleshed out "what" and "why"(and a little bit of the "how," however this can be discussed more as we move more into implementation details).

**Comment by sunjayBhatia** [comment]
Adding that this issue needs a design, since it looks like it would be helpful to do a formal design proposal to iron out the details of this new feature/api we will be providing and @bwu-contour expressed interest in going through this more formal process
