### ISSUE TITLE
Envoy Route Testing tool compatibility for Contour

### ISSUE THREAD

**Issue by clayton-gonsalves** [projectcontour/contour#6268]
Envoy provides a route testing tool through which you can test routing logic.
Reference: https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/tools/router_check#config-tools-router-check-tool

This tool is run against raw envoy route configs. 

it would be helpful for the community if contour could generate raw routing rules(given an HTTPProxy/ingress/gateway and services) to be tested against this tool. 

This tool can be useful in dev workflows, ci tests etc.

**Comment by sunjayBhatia** [comment]
Just took a look at the first PR for this and it looks great overall, probably just some minor comments to come

I think we'll probably want to add a few tasks to this issue to complete before calling it fully done:
- since cluster name readability is an issue, IMO to have confidence the routegen tool generated what is being tested, we should add the k8s Service namespace/name to the cluster [metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-metadata), similar to how we add the originating configuration kind and namespace/name to routes
- add Gateway API resource support/testing
- add Ingress testing
- add an e2e test
